### ISSUE TITLE
Radical of an ideal

### ISSUE THREAD

**Issue by ahumenberger** [oscar-system/Singular.jl#101]
Is there already a way to compute the radical of an ideal?
I didn't find anything. I also had a look in the Singular source, and the only thing I found was the following file where algorithms for computing the radical are implemented:
https://github.com/Singular/Sources/blob/6391ebdfc684a1e7384c830df2b18aae61eedccc/Singular/LIB/primdec.lib
However, that's not a C/C++ file which can be easily called from within Julia, or is it?

**Comment by wbhart** [comment]
No, unfortunately that's not in the kernel. Does @hannes14 know of anything in the kernel?

I guess we need to get libraries working soon!

**Comment by fingolfin** [comment]
Libraries have been supported for some time now. Just recently, a function `radical()` was added to Oscar.jl in https://github.com/oscar-system/Oscar.jl/pull/227 -- you can look there to see how to do it in "pure" Singular.jl, should you prefer that. (Assuming you still care, after almost 2 years... :-( )
