### ISSUE TITLE
minres() does not work as expected

### ISSUE THREAD

**Issue by steenpass** [oscar-system/Singular.jl#114]
After applying `minres()`, Singular.jl still prints the old, non-minimal resolution:
```julia
julia> using Singular

julia> R, (w, x, y, z) = PolynomialRing(QQ, ["w", "x", "y", "z"])
(Singular Polynomial Ring (QQ),(w,x,y,z),(dp(4),C), spoly{n_Q}[w, x, y, z])

julia> I = Ideal(R, w^2 - x*z, w*x - y*z, x^2 - w*y, x*y - z^2, y^2 - w*z)
Singular Ideal over Singular Polynomial Ring (QQ),(w,x,y,z),(dp(4),C) with generators (w^2-x*z, w*x-y*z, x^2-w*y, x*y-z^2, y^2-w*z)

julia> F = fres(std(I), 3)
Singular Resolution:
R^1 <- R^5 <- R^6 <- R^2

julia> M = minres(F)
Singular Resolution:
R^1 <- R^5 <- R^6 <- R^2
```
However, `betti()` gives the correct (that is, minimal) result:
```julia
julia> B = betti(M)
3×4 Array{Int32,2}:
 1  0  0  0
 0  5  5  0
 0  0  0  1
```
Internally this is due to the fact that `libSingular.syMinimize(ptr, ...)` sets `ptr->minres` and returns `ptr`.

**Comment by wbhart** [comment]
There's a very large patch being worked on by Sebastian that overhauls the resolutions, I believe.

**Comment by wbhart** [comment]
This still returns the wrong answer in the latest version of Singular.jl, v0.4.2 (I am using Julia 1.3.1 on WSL).

**Comment by wbhart** [comment]
The current implementation of syMinimize in libsingular_julia in https://github.com/oscar-system/libsingular-julia/blob/master/singular.cpp is:

```
Singular.method("syMinimize", [](syStrategy ra, ring o) {
        const ring origin = currRing;
        rChangeCurrRing(o);
        syStrategy result = syCopy(ra);
        syMinimize(result);
        rChangeCurrRing(origin);
        return result;
    });
```

The implementation of syMinimize in https://github.com/oscar-system/Singular.jl/blob/master/src/libsingular/resolutions.jl is

```
function syMinimize(r::resolvente, length::Cint, R::ring)
   icxx"""const ring origin = currRing;
          syStrategy temp = (syStrategy) omAlloc0(sizeof(ssyStrategy));
          resolvente result;
          rChangeCurrRing($R);
          temp->fullres = (resolvente) omAlloc0(($length + 1)*sizeof(ideal));
          for (int i = $length - 1; i >= 0; i--)
          {
             if ($r[i] != NULL)
                temp->fullres[i] = idCopy($r[i]);
          }
          temp->length = $length;
          syMinimize(temp);
          result = temp->minres;
          temp->minres = NULL;
          /* syMinimize increments this as it returns a value we ignore */
          temp->references--;
          syKillComputation(temp, $R);
          rChangeCurrRing(origin);
          result;
       """
end
```

Therefore the reason given in the original report for the bug seems to be incorrect. As far as I can see we return temp->minres, which should be the minres, not the original resolution.

Perhaps @hannes14 could take a look at these and tell us what we are doing wrong.

**Comment by hannes14** [comment]
Singular.method("syMinimize", [](syStrategy ra, ring o) {
        const ring origin = currRing;
        rChangeCurrRing(o);
        syStrategy result = syCopy(ra); // increments a ref count
        syMinimize(result); // check if result->minres is set, compute and set it if not
        rChangeCurrRing(origin);
        return result;
    });

This routine does not create a new, minimal resolution, but checks, if the resolution is already
minimal. If not, the structure is changed to contain additionally the data of the minimized resolution.
syStrategy (result) has 2 members for the resolution data: result->fullres and result->minres,
the libSingular routines get_minimal_res and get_full_res gives access to the data
(as array of ideal).

**Comment by wbhart** [comment]
Does it copy fullres into minres if it is already minimal? If so, our code should work.

At any rate I guess the solution will be to add get_minimal_res to libsingular.jll and then change the way we handle resolutions.

**Comment by hannes14** [comment]
Am Mon, Jan 11, 2021 at 03:22:31AM -0800 schrieb wbhart:
> Does it copy fullres into minres if it is already minimal? If so, our code should work.
The check is simply checking the part minres==NULL - if so,
compute the minimal resultion, which may be equal to the part fullres.

**Comment by wbhart** [comment]
Right, but the syMinimize function always sets that back to NULL after use, so it should always be NULL before asking for a minres. So I don't see what is going wrong, actually.

**Comment by wbhart** [comment]
@hannes14 Am I right that omAlloc0 sets everything in temp to 0? If so, then ->minres should always be NULL before Singular's syMinimize is called.

Also, is it suspicious that the call the syMinimize doesn't pass the ring? I'm not even sure what it is calling at that point.

**Comment by hannes14** [comment]
Yes, omalloc0 returns a memory block filled with 0.
Then the function syMinimize from https://github.com/oscar-system/Singular.jl/blob/master/src/libsingular/resolutions.jl creates a new (empty) resolution, copies the fullres part from th input,
computes the minimal resolution and return this (array of ideal). temp is removed at the end.

**Comment by wbhart** [comment]
Then why doesn't it work?
