### ISSUE TITLE
Equality of ideals

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#116]
Is the following intended?

```
julia> import Singular;
julia> R,(x) = Singular.PolynomialRing(Singular.QQ, ["x"]);
julia> I1 = Singular.Ideal(R, x);
julia> I2 = Singular.Ideal(R, x);
julia> I1==I2
false
```

**Comment by wbhart** [comment]
For the time being, yes. Testing equality of ideals is incredibly slow, so
you have to use isequal or equal, for which you have to look at the
documentation. It's to prevent people from accidentally checking equality
under the false impression that it is a cheap operation.

**Comment by fieker** [comment]
On Wed, Jun 26, 2019 at 03:10:52AM -0700, wbhart wrote:
> For the time being, yes. Testing equality of ideals is incredibly slow, so
> you have to use isequal or equal, for which you have to look at the
> documentation. It's to prevent people from accidentally checking equality
> under the false impression that it is a cheap operation.
> 

This is a Singular problem. For Oscar we clearly agreed in == for ideals
to do the mathematical thing.
Even in Singular, it should at least compare the generators.

**Comment by hannes14** [comment]
No, Singular decided not to try this:
- I==J results in an error
- matrix(I)==matrix(J) compares the generators
- isEqualIdeal(I,J) compares the ideals (mathematically)

**Comment by fieker** [comment]
On Wed, Jun 26, 2019 at 04:58:36AM -0700, Hans Schoenemann wrote:
> No, Singular decided not to try this:
> - I==J results in an error
Then this is missing in Singular.jl

**Comment by wbhart** [comment]
Nothing is missing. It was a deliberate decision to not define == for the reasons I stated.

@hannes14 is talking about Singular, not Singular.jl, I think.

Oscar can define equality however it likes, and it merely has to call the appropriate function here, though I would like to point out that these are Singular ideals, which Oscar doesn't want.

**Comment by fieker** [comment]
On Wed, Jun 26, 2019 at 05:34:07AM -0700, wbhart wrote:
> Nothing is missing. It was a deliberate decision to not define == for the reasons I stated.
The problem is not that you (we) did not define ==, but that it is
automatically defined and results in garbage...

No-one is ever going to read the doc for == until (s)he spend a long
time hunting down a strange bug.

**Comment by wbhart** [comment]
I agree with that. I'm happy to have it print an error message instead.

My understanding is that the expert commutative algebra people tell me that mathematical equality of ideals is not the thing you usually want. Rather, comparison of generators is used more frequently.

To avoid confusion, we decided to not define == at all. But you are right. It should instead return a helpful error message, e.g. I propose, "== not defined for ideals, please use equal or isequal (see the documentation for details)".

**Comment by wbhart** [comment]
I checked and Oscar.jl can override the definition of == provided by Singular.jl, so long as Oscar.jl does "import Singular" instead of "using Singular", even if it imports == from Base.

So this is good news. It means Oscar is fully customizable to our requirements without affecting the underlying packages.

I suggest we use metaprogramming to import the symbols we need from our various packages.

**Comment by fieker** [comment]
On Wed, Jun 26, 2019 at 07:08:32PM -0700, wbhart wrote:
> I checked and Oscar.jl can override the definition of == provided by Singular.jl, so long as Oscar.jl does "import Singular" instead of "using Singular", even if it imports == from Base.
Good. I still think Singular.jl is stupid there, but that's their
decision.
> 
> So this is good news. It means Oscar is fully customizable to our requirements without affecting the underlying packages.
> 
> I suggest we use metaprogramming to import the symbols we need from our various packages.
Check the Hecke.jl, Nemo.jl there we already do this...

**Comment by wbhart** [comment]
It will now print an error message, and Oscar can define equality however it likes.

**Comment by tthsqe12** [comment]
Use `Singular.isequal(I1, I2)` for the cheap equality of lists of generators, and use `Singular.equal(I1, I2)` for the expensive actual equality of mathematical ideals.
