### ISSUE TITLE
unique polynomials

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#120]
Is the following expected?

```
julia> using Singular

Welcome to Nemo version 0.14.0

Nemo comes with absolutely no warranty whatsoever


julia> R,(x,y) = Singular.PolynomialRing(Singular.QQ, ["x","y"]);

julia> unique([x+y-y, x])
2-element Array{spoly{n_Q},1}:
 x
 x
```

**Comment by wbhart** [comment]
Not really. But it is probably due to a missing hash function or something like that.

**Comment by sebasguts** [comment]
Yep, it is indeed because of the missing hash function. You can do this by overloading `Base.hash`, making it always return `0` for Singular polynomials.

**Comment by wbhart** [comment]
Better still would be to provide a working hash!

**Comment by sebasguts** [comment]
Absolutely, yes. But as long as we do not have one, a hash that is not compatible with `==` is worse than no hash.

**Comment by kalmarek** [comment]
@wbhart I'd like to point out that hash is required in the ring interface;
and Singular polys are by no means the only type which does not define it.

why don't we define `Base.hash(::RingElem, h::UInt) = h` (or actually for all types we define!) and in the interface just ask to provide a better function?

**Comment by wbhart** [comment]
Why don't we just add hash functions for types that don't have them?

I don't understand this desire to implement trivial hashes. They are so terribly easy to implement properly, and there are plenty of examples.

**Comment by kalmarek** [comment]
I don't understand why we should stick to the definition which (while with some merits based on performance) gives false mathematical results. And as we can see it's very easy to forget to define hash AND to find out which types don't define it.

you don't have to take my word for it; just count the number of issues referencing this one: [custom hashing is too easy to accidentally break](https://github.com/JuliaLang/julia/issues/12198)

and now there are n+1 of them ;-)

**Comment by wbhart** [comment]
I don't want to stick with the incorrect definition. But why waste all that effort to add trivial hash functions and tests and not the extra couple of lines to do it properly?

**Comment by fieker** [comment]
On Thu, Jun 27, 2019 at 03:01:34PM -0700, wbhart wrote:
> I don't want to stick with the incorrect definition. But why waste all that effort to add trivial hash functions and tests and not the extra couple of lines to do it properly?
> 
Why haven't we done it already if it is trivial?

Point is: even we did not manage over the last years to implement hashes
for all our types, thus to implement a generic trivial one would be an
improvement. I agree that this might produce a false sense of security,
but if even we cannot manage to do it the 1st time round, then why do we
believe other users will do it correctly?

**Comment by kalmarek** [comment]
@wbhart adding a correct fallback does not preclude us from providing specific hashes for particular types

**Comment by fingolfin** [comment]
I support @kalmarek's suggestion as well
