### ISSUE TITLE
Provide an up to date version of the documentation

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#125]
As I understand from the comment https://github.com/oscar-system/Singular.jl/pull/112#issuecomment-505378804 the documentation for Singular.jl is not available online and there is some documentation available there. Currently the documentation contains the URL http://wbhart.github.io/Singular.jl/ for online-documentation. However I do did not check whether it is up to date.

Suggestion: Can we centralize deployment of documentation and make it available under  the following URL?

http://oscar-system.github.io/Singular.jl/

**Comment by wbhart** [comment]
Yes, we can do this. Someone needs to get around to setting up the gh-pages account and sorting out the deployment. It's on a very long list of things....

**Comment by fingolfin** [comment]
I've implemented this some time ago (without being aware of this issue). There are links in the README.md now to https://oscar-system.github.io/Singular.jl/dev/ and https://oscar-system.github.io/Singular.jl/stable/
