### ISSUE TITLE
Different data types for univariate/multivariate polynomials

### ISSUE THREAD

**Issue by raulepure** [oscar-system/Singular.jl#126]
When asking for the type of variables the following is returned in the univariate case:
`julia> R , (x) = Singular.PolynomialRing(Singular.QQ, ["x"])
(Singular Polynomial Ring (QQ),(x),(dp(1),C), spoly{n_Q}[x])

julia> typeof(x)
Array{spoly{n_Q},1}`

and the following in the multivariate case:
`julia> R , (x, y) = Singular.PolynomialRing(Singular.QQ, ["x", "y"])
(Singular Polynomial Ring (QQ),(x,y),(dp(2),C), spoly{n_Q}[x, y])

julia> typeof(x)
spoly{n_Q}`

The data type should be the same.

**Comment by fieker** [comment]
On Fri, Jul 19, 2019 at 01:37:08AM -0700, raulepure wrote:
> When asking for the type of variables the following is returned in the univariate case:
> `julia> R , (x) = Singular.PolynomialRing(Singular.QQ, ["x"])
> (Singular Polynomial Ring (QQ),(x),(dp(1),C), spoly{n_Q}[x])
> 
> julia> typeof(x)
> Array{spoly{n_Q},1}`
> 
> and the following in the multivariate case:
> `julia> R , (x, y) = Singular.PolynomialRing(Singular.QQ, ["x", "y"])
> (Singular Polynomial Ring (QQ),(x,y),(dp(2),C), spoly{n_Q}[x, y])
> 
> julia> typeof(x)
> spoly{n_Q}`
> 
> The data type should be the same.
Nope. In the 1st case, you probably wat (x, ) to get what you want.
(x) is no tuple in julia, (x, ) is a tuple of length 1...
