### ISSUE TITLE
Constructors for CoefficientRing non-existent

### ISSUE THREAD

**Issue by FabianMaeurer** [oscar-system/Singular.jl#131]
In the documentation it says, that it's possible to coerce Nemo/AbstractAlgebra rings to Singular.CoefficientRing by something like

R, x = Nemo.PolynomialRing(ZZ, "x")
S = CoefficientRing(R)
t = S(x)

But trying this it seems that the constructor is not defined.

**Comment by wbhart** [comment]
Yes, unfortunately this code is currently inactive because of the rewrite of Singular.jl to use CxxWrap instead of Cxx. It will be reenabled eventually (hopefully in a month or two at most).

Sorry for the inconvenience.
