### ISSUE TITLE
Implement high level wrapper of bigintmat

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#154]
This is currently missing, even though the caller needs big integer matrices for some Singular library functions.

Therefore we should write a wrapper for bigintmat, just as we have high level wrappers for other Singular types.

**Comment by tthsqe12** [comment]
@hannes14 Are there any kernel functions using bigintmat that people would want to use?
If they are not used by the kernel and the only use of bigintmat is via the library calls, then I am perfectly happy converting to and from fmpz_mat or Matrix{BigInt} for the library calls.

**Comment by hannes14** [comment]
Am Wed, Jul 21, 2021 at 12:00:16PM -0700 schrieb dan:
>    @hannes14 Are there any kernel functions using bigintmat that people would
>    want to use?
bigintmat and bigint as result types are used in Singulars kernel for:
- det, bareiss, factorization (in ZZ)
- general operations: +,-,*,div,mod,transpose,CRT, conversions to/from other types

**Comment by tthsqe12** [comment]
I am closing this as I don't think the full matrix interface is worth doing. Singular.jl should now have the conversions between sbigintmat and fmpz_mat/Matrix{BigInt}, and if you want to do heavy matrix calculations the latter are the way to go.
