### ISSUE TITLE
n_unknown: ring or field

### ISSUE THREAD

**Issue by raulepure** [oscar-system/Singular.jl#170]
At the moment we have no method to know, whether a coefficient ring of n_unknown type is a ring or field. It treats Nemo.ZZ and Nemo.QQ in the same way, whereas some algorithms rely on the fact, that we need a coeficient field and not a ring.
This needs to be fixed at some point.

**Comment by hannes14** [comment]
libSingular provides this information: nCoeff_is_Ring(const coeffs cf)

**Comment by wbhart** [comment]
He's just talking about the fact that in Singular.jl n_unknown belongs to
Singular.RingElem even if it wraps a Nemo.FieldElem. We'll have to make two
types out of it, as this info is required at compile time.

**Comment by tthsqe12** [comment]
Yes, I see. We want the last return to be true.
```julia
julia> using Singular

julia> R, (x, y) = PolynomialRing(Singular.Nemo.FractionField(Singular.Nemo.QQ["t"][1]), ["x", "y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_unknown{AbstractAlgebra.Generic.Frac{Nemo.fmpq_poly}}}[x, y])

julia> base_ring(R)
Singular coefficient ring over Fraction field of Univariate Polynomial Ring in t over Rational Field

julia> ans isa Singular.Nemo.Field
false
```

**Comment by tthsqe12** [comment]
To be clear: the answer to this issue's title is "yes".
