### ISSUE TITLE
Extracting constants from Singular polynomial rings over Nemo fields

### ISSUE THREAD

**Issue by johannes-hoffmann** [oscar-system/Singular.jl#172]
Assume `R` is a `Singular.PolynomialRing` over a `Nemo.Field` called `K`. Is there a way to coerce constant polynomials in `R` back to `K`?
Example:
```
K = Nemo.QQ
R, (x, y) = Singular.PolynomialRing(K, ["x", "y"])
a = R(5)
```
and I would like to extract `K(5)` from `a` (`K(a)` did not work).

**Comment by wbhart** [comment]
Good idea. There isn't such a thing at present, at least not a supported interface.  I think if c is such a coefficient, julia(c.ptr) might do the job, but I am not sure. This is obviously not ideal, even if it works.

**Comment by tthsqe12** [comment]
There is a more fundamental error here:
```julia
julia> K = Singular.Nemo.QQ
Rational Field

julia> R, (x, y) = Singular.PolynomialRing(K, ["x", "y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_unknown{Nemo.fmpq}}[x, y])

julia> base_ring(R) == K
false
```

@wbhart @thofma Any objection to me fixing this so that `base_ring(R) == K` returns true. The n_unknown should be an "invisible wrapper" ...

**Comment by thofma** [comment]
Fine with me.
