### ISSUE TITLE
Check for C++ compiler being recent  enough and supporting C++14 (for CxxWrap.jl)

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#181]
The CxxWrap module has to be compiled outside of BinaryBuilder as linking is done against the user's Julia (the location of which we do not know at BinaryBuilder time). For this, we need at least cmake and C++. We should add a test for these and add a helpful message if they are not found.

**Comment by fingolfin** [comment]
We get CMake "for free" via CMake.jl (and I changed our build.jl to use that some time ago). So "only" the C++ compiler remains

**Comment by fingolfin** [comment]
This has been resolved by the moved to JLLs
