### ISSUE TITLE
Inconsistency for conversion

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Singular.jl#188]
This is inconsistent:
```julia
julia> using Singular

Welcome to Nemo version 0.16.1

Nemo comes with absolutely no warranty whatsoever

julia> Singular.QQ(1)
1

julia> c = Singular.QQ(1)
1

julia> numerator(c), typeof(numerator(c))
(1, n_Z)

julia> c, typeof(c)
(1, n_Q)

julia> convert(Rational{BigInt}, c)
ERROR: MethodError: Cannot `convert` an object of type n_Q to an object of type Rational{BigInt}
Closest candidates are:
  convert(::Type{Rational{BigInt}}, ::Nemo.fmpq) at /Users/sascha/.julia/packages/Nemo/5aSWJ/src/flint/fmpq.jl:831
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  ...
Stacktrace:
 [1] top-level scope at REPL[5]:1

julia> Rational{BigInt}(c)
1//1

julia> numerator(c), typeof(numerator(c))
(1, n_Z)

julia> BigInt(numerator(c))
ERROR: MethodError: no method matching BigInt(::n_Z)
Closest candidates are:
  BigInt(; nbits) at gmp.jl:56
  BigInt(::BigInt) at gmp.jl:256
  BigInt(::Union{Int32, Int64}) at gmp.jl:287
  ...
Stacktrace:
 [1] top-level scope at REPL[8]:1

julia> convert(BigInt, numerator(c))
1
```

**Comment by fieker** [comment]
Apart from agreeing that this is inconsitent, do we care?
I'd have thought that Rational{BigInt} is a julia type, not a
"supported" Oscar type (would be fmpq).
I don't think we wil be able to convert everything to everything,
ever...

Is there a use case?

**Comment by wbhart** [comment]
Thanks for the report. Agreed, this is inconsistent.

What I have been doing up to this point is using R(a) for cases where a canonical conversion/coercion is possible without losing data (for any value of a). In cases where a conversion is possible but only in some cases, I use the convert function.

However, someone pointed out that in some contexts if you supply one you get the other for free (at least when using types and not parent objects), and I probably have this the wrong way around if I want to be consistent with that. So at the moment the whole conversion system probably needs a workover.

But this ticket will serve as a reminder that we need to sort this out when we get around to fixing this.

For the time being I would happily accept a PR to add one or the other of the missing function as you see fit.

**Comment by rfourquet** [comment]
I think this is solved (the snippets in the OP don't error out on the master branch).

**Comment by thofma** [comment]
OK, let's close this.
