### ISSUE TITLE
Path of Singular binary

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/Singular.jl#198]
Is it possible to get the absolute path of the Singular binary `deps/usr/bin/Singular`?

**Comment by wbhart** [comment]
The Julia function abspath will give the absolute path corresponding to a relative path:

https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.abspath

Hopefully this link gives you the other info you need:

https://discourse.julialang.org/t/path-of-this-package/16401

**Comment by fieker** [comment]
On Tue, Feb 25, 2020 at 07:52:37AM -0800, Mohamed Barakat wrote:
> Is it possible to get the absolute path of the Singular binary `deps/usr/bin/Singular`?
> 
julia> pathof(Hecke)
"/home/fieker/.julia/dev/Hecke/src/Hecke.jl"

and then joinpath/ splitpath

**Comment by mohamed-barakat** [comment]
Perfect, works:

`joinpath(splitdir(splitdir(pathof(Singular))[1])[1],"deps/usr/bin/")`

Thank you both very much.
