### ISSUE TITLE
ERROR: LoadError: Failed to precompile Singular

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/Singular.jl#202]
I now keep getting build failures for `HomalgProject.jl` on travis with the error 

`ERROR: LoadError: Failed to precompile Singular`

https://travis-ci.com/homalg-project/HomalgProject.jl/jobs/294118839

The log shows problems with `CxxWrap`

```
│ /home/travis/.julia/packages/CxxWrap/lDNAy/deps/usr/include/jlcxx/type_conversion.hpp:203:43: error: expected template-name before ‘<’ token
...
│ make[2]: *** [CMakeFiles/singularwrap.dir/singular.cpp.o] Error 1
```
Is this a known issue?

**Comment by wbhart** [comment]
No, everything should be fine. Do you specify a version number for Singular.jl or CxxWrap.jl in your Project.toml? If so, perhaps you need to update them.

**Comment by mohamed-barakat** [comment]
I am requiring

```
[compat]
julia = "1.1, 1.2, 1.3"
GAP = "^0.2.6"
Singular = "0.1, 0.2"
```
https://github.com/homalg-project/HomalgProject.jl/blob/master/Project.toml

Do you see a mistake?

**Comment by wbhart** [comment]
You have to add CxxWrap (the latest version). Probably it is using an older version.

**Comment by mohamed-barakat** [comment]
I thought since the released `Singular.jl` v0.2.0 is requiring `CxxWrap` I do not need to require any such dependency

```
[compat]
AbstractAlgebra = "^0.8.0"
Nemo = "^0.16.0"
julia = "1.0, 1.1, 1.2"
CxxWrap = "^0.8.1"
BinaryProvider = "^0.5.8"
```

**Comment by wbhart** [comment]
Yes, that should be correct, at least with the latest Singular,jl. But I don't see any other explanation for the problem.

By the way, you want:

CxxWrap = "^0.9"

which of course implies Singular 0.2.

**Comment by mohamed-barakat** [comment]
Under

https://github.com/JuliaInterop/CxxWrap.jl/releases
 
in the section **Breaking changes** for v0.9.0 it mentions `IsMirroredType` which seems to be the reason for the CxxWrap error in the above log:

* IsMirroredType instead of IsImmutable and IsBits, added using map_type.

By default, IsMirroredType is true for trivial standard layout types, so if you want to wrap these normally
(i.e. you get an unexpected error Mirrored types (marked with IsMirroredType) can't be added using add_type, map them directly to a struct instead and use map_type) then you have to explicitly disable the mirroring for that type:
template<> struct IsMirroredType<Foo> : std::false_type { };

**Comment by wbhart** [comment]
The latest Singular handles all that. Unless you are using CxxWrap directly, you don't need to worry about any of that.

My guess is for some reason it is still using Singular 0.1 with the latest Julia. You could try removing 0.1 from your Singular.jl compat instead of adding the dependency on CxxWrap.

**Comment by wbhart** [comment]
Another thing you might try is to delete the directory .julia/clones

Then remove Singular and CxxWrap from your system and try again. By remove I mean go into package mode and free Singular and rm Singular, same with CxxWrap.

**Comment by wbhart** [comment]
Oh don't worry, I see that your problem is with travis, not a local machine. That won't be relevant.

**Comment by wbhart** [comment]
Actually, I think I have figured out the problem. The gcc Travis uses by default is not compatible with CxxWrap 0.9. If you add the following at the beginning of your Project.toml the problem should go away:

# Force Ubuntu 18.04 "Bionic" to get even newer GCC, binutils etc.
dist: bionic

**Comment by wbhart** [comment]
That first line is just a comment with a hash character. GitHub interprets it as Markdown, which is why it is bold with an underline.

**Comment by mohamed-barakat** [comment]
Thank you very much Bill. I allowed myself to change your post and quoted the corresponding segment.

**Comment by mohamed-barakat** [comment]
Your comments resolved the issue. Thanks again Bill.
