### ISSUE TITLE
Singular.jl does not work with Julia 1.4

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Singular.jl#209]
There are CxxWrap related errors while compiling as one can see in the [Travis logs](https://travis-ci.com/github/oscar-system/Singular.jl), where a segfault during precompilation apparently happens. I assume this is related to https://github.com/JuliaInterop/CxxWrap.jl/issues/214 (perhaps @saschatimme @benlorenz @kalmarek know better, though?)

**Comment by saschatimme** [comment]
Yep, its the same thing. Things should work with CxxWrap master and a new release of CxxWrap should also be ready soon.

**Comment by fingolfin** [comment]
This is working now. Not sure why, but it is.
