### ISSUE TITLE
Is `Pkg.add("Singular")` supposed to work?

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#217]
I get lots of CxxWraps errors when doing `Pkg.add("Singular")` but I don't know if this is expected or not? I tried on julia 1.0 and julia 1.3. For example, https://travis-ci.org/github/ederc/GB.jl/builds/675341671

This is a package which has Singular as a dependency.

**Comment by fieker** [comment]
My guess is that the c++ compiler is too old. Same as for polymake, it needs to support c++-17, hence the debian 16.04 default is too old

**Comment by thofma** [comment]
Thanks, adjusted the Ubuntu version of travis and it works.
