### ISSUE TITLE
A simple code. How to translate to Julia code?

### ISSUE THREAD

**Issue by gangchern** [oscar-system/Singular.jl#225]
The following is the singular code for the Milnor number. 
```
ring r=0,(x,y),ds; 
poly f=x5+y5+x2y2;
ideal j=jacob(f);
vdim(std(j));
```

The I try to write it in julia. What is the corresponding julia code? How to set the ring or field to be complex number or real number?  I can not find the corresponding function in the document. Is there any dict  for the function names?

**Comment by wbhart** [comment]
You can create complex numbers with CC = Nemo.ComplexField(128) for example. I'm not sure if this will actually do what you want though.

The documentation covers how to create polynomial rings, polynomials and ideals. Most of the other names should be the same as Singular.
