### ISSUE TITLE
Banner shows Julia version not Singular version

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/Singular.jl#226]
```julia
julia> using Singular
Singular.jl, based on
                     SINGULAR                                 /
 A Computer Algebra System for Polynomial Computations       /
                                                           0< 1.4.0
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
```

**Comment by fieker** [comment]
On Mon, Apr 27, 2020 at 04:32:46PM -0700, Mohamed Barakat wrote:
I implemented a first, bad banner hopeing that some singular guru would
do a better job. This too is the singular log, singular.jl should be
different, e.g. Greuel and Pfister should appear...

**Comment by fingolfin** [comment]
"Greuel and Pfister should appear" ? Or not appear?

**Comment by fieker** [comment]
On Wed, Apr 29, 2020 at 04:41:36AM -0700, Max Horn wrote:
> "Greuel and Pfister should appear" ? Or not appear?
On Singular: yes
On Singular.jl: no
In summary: I don't know...

**Comment by fingolfin** [comment]
Well, that's something @wdecker should decide...

@mohamed-barakat in the current master branch, @fieker and @hannes14 fixed this, it now shows this for me:
```
julia> using Singular
Singular.jl, based on
                     SINGULAR                                 /
 A Computer Algebra System for Polynomial Computations       /  Singular.jl: 0.3.0
                                                           0<   Singular   : 4.2.1-4
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \


julia>
```
Though I note that it's a bit odd this way: it says
> Singular.jl, based on
then goes on to show a Singular banner, which somehow also includes the Singular.jl version. Might make more sense like this?
```
Singular.jl 0.3.0, based on
                     SINGULAR                                 /
 A Computer Algebra System for Polynomial Computations       /
                                                           0<   Singular   : 4.2.1-4
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
```

**Comment by fieker** [comment]
On Wed, Apr 29, 2020 at 04:59:09AM -0700, Max Horn wrote:
> Well, that's something @wdecker should decide...
> 
> @mohamed-barakat in the current master branch, @fieker and @hannes14 fixed this, it now shows this for me:
> ```
> julia> using Singular
> Singular.jl, based on
>                      SINGULAR                                 /
>  A Computer Algebra System for Polynomial Computations       /  Singular.jl: 0.3.0
>                                                            0<   Singular   : 4.2.1-4
>  by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
> FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> 
> 
> julia>
> ```
> Though I note that it's a bit odd this way: it says
> > Singular.jl, based on
> then goes on to show a Singular banner, which somehow also includes the Singular.jl version. Might make more sense like this?
> ```
> Singular.jl 0.3.0, based on
>                      SINGULAR                                 /
>  A Computer Algebra System for Polynomial Computations       /
>                                                            0<   Singular   : 4.2.1-4
>  by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
> FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> ```
> 
It was done to show the information s.w. and to motivate the Singular
"community" to do better. Some unnamed people already complained about
the names shown - and absent, implying that times have changed.
Attributing this to the Singular team, the oscar-project, the
tooth-fairy... is possibly better

**Comment by mohamed-barakat** [comment]
> Though I note that it's a bit odd this way: it says
> 
> > Singular.jl, based on
> > then goes on to show a Singular banner, which somehow also includes the Singular.jl version. Might make more sense like this?
> 
> ```
> Singular.jl 0.3.0, based on
>                      SINGULAR                                 /
>  A Computer Algebra System for Polynomial Computations       /
>                                                            0<   Singular   : 4.2.1-4
>  by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
> FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> ```

I also would prefer it this way. And then you one could add further attributions to the first line if desired.

**Comment by wbhart** [comment]
If this is seriously how the Singular.jl banner is going to look, the Nemo.jl banner is going to have to change to include the Flint authors.
