### ISSUE TITLE
Add Weyl and Exterior algebras

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#245]
- [x] Add low level libSingular wrappers of Singular's rWeyl and rExterior (This was the wrong approach, just use pural functionality)
- [x] Add high level pweyl and pexterior types (There is no pexterior and they is spuralg for plural polys)
- [x] Add high level ExteriorAlgebra and WeylAlgebra ring types (Again, the wrong approach with ExteriourAlgebra, it is GAlgebra)
- [x] Make AbstractAlgebra accept non-commutative algebras in its MPoly iterators see https://github.com/Nemocas/AbstractAlgebra.jl/issues/603
- [x] Add documentation for Weyl and Exterior algebras to Singular.jl (Noncommutative section)
- [x] Add test code for Weyl and Exterior algebras to Singular.jl (No to ExteriorAlgebra and yes to GAlgebra)
- [x] Should quotient rings over Weyl and Exterior algebras be allowed in the code? (Yes, and its G-algebra instead of exterior algebra)
- [x] Should Weyl and Exterior algebras be restricted to being over a field? (let's allow rings and find out what is broken)
- [x] Replace spoly with polyalg for all arithmetic in poly/poly.jl that makes sense for algebras (It's SPolyUnion, possibly a bad name)
- [x] Change docstrings for poly.jl functions that also work over algebras
- [x] Wrap other Singular functionality for Singular Weyl and Exterior algebras

**Comment by tthsqe12** [comment]
@hannes14 For the last two points, could you at some point guide us on what functions also work on PLURAL and LETTERPLACE rings? The type names are here https://oscar-system.github.io/Singular.jl/latest/noncommutative/
and for example, in https://github.com/oscar-system/Singular.jl/pull/513 I was fairly certain the "Differential functions" only work on spoly (and not spluralg, and slpalg).

**Comment by hannes14** [comment]
functions for spluralg (from src/ideal/ideal.jl, functions with @doc):
-gens,iszero,isconstant,isvar_generated,normalize!,+,*,  (p*I has wrong order),^,contains,
 isequal, equal,lead,intersection,quotient,saturation,slimgb,std,interreduce,reduce,eliminate,
 kernel,syz,lift_std_syz,lift_std,jet,vdim,kbase,highcorner,

functions for slpalg:
-gens,iszero,isconstant,isvar_generated,normalize!,+,*,contains,isequal, equal,lead,std,
reduce,syz,
