### ISSUE TITLE
Switch Singular.jl from SingularBuild to Singular_jll;  create and use `libsingular_jll.jl

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Singular.jl#254]
Right now, for Singular.jl we use a custom made Singular binary created via https://github.com/oscar-system/SingularBuilder. It would be good to switch from that to using [`Singular_jll.jl`](https://github.com/JuliaBinaryWrappers/Singular_jll.jl) instead, for multiple reasons; in particular, we'd then finally have the same GMP, MPFR, FLINT, ... in all Oscar packages, see also <https://github.com/oscar-system/Oscar.jl/issues/109>. (well, almost all, once also GAP.jl has been completely switched over to JLLs; I am still working on this, but keep uncovering things that Julia does not yet provide; on the upside, things *are* improving, and with the next LTS of Julia, 1.6, I believe all pieces will finally be fully in place). 

But we can actually go one step further, and follow what @benlorenz has been doing for `Polymake.jl`: that is, move the CxxWrap stuff in the `deps` dir to a separate JLL package, too (see https://github.com/oscar-system/libpolymake-julia and https://github.com/oscar-system/libpolymake-julia and https://github.com/oscar-system/Polymake.jl/pull/308).

That way, installing `Singular.jl` would not require a C/C++ compiler anymore, nor would any compilation take place on the user's system. 

I am hoping that perhaps @hannes14 or @tthsqe12 could work on this, with help/advice from @benlorenz @thofma and myself.

CC @fieker @wdecker

**Comment by tthsqe12** [comment]
Sure. It will be a learning experience. By the way, it might not have been clear from the meeting, but if flint is compiled against < gmp 6.2 and then run with gmp 6.2, it will crash. Latest julia seems to be using gmp 6.3

**Comment by fingolfin** [comment]
No, that wasn't clear at all. Do you know what exactly is the cause of the crash? (And Julia 1.6 will use GMP 6.2, yeah).

**Comment by thofma** [comment]
Thw problem is that the binaries were build with GMP 6.1.2. We probably know how to fix it and are currently running some experiments. Also, it is not a problem for Singular, as it is only a problem on Windows.

**Comment by wbhart** [comment]
GMP changed the way they allocate mpz's from 6.1 to 6.2 (so-called lazy allocation). As Flint requires a compatibility layer to use GMP on various systems, it needs to allocate and deallocate mpz's the same way GMP does, otherwise there will be a crash. Therefore if you build against one version of GMP you can't use another at runtime.

**Comment by fingolfin** [comment]
@wbhart that sounds like a bug in the FLINT GMP compatibility, though. Indeed, looking at it, it should be trivial to change it so that it works with both GMP 6.1 and 6.2 at runtime, regardless of which version of GMP was used to compile FLINT.

**Comment by fingolfin** [comment]
See https://github.com/wbhart/flint2/pull/814

**Comment by wbhart** [comment]
@fingolfin No bug. Please see the GMP sonames. 6.2.0 is not binary compatible with 6.1.2.

#        6.0.0   12:0:2    8:0:4     -
#        6.1.0   13:0:3    9:0:5     -
#        6.1.1   13:1:3    9:1:5     -
#        6.1.2   13:2:3    9:2:5     -
#        6.2.0   14:0:4   10:0:6     -

According to their numbering, interfaces were added in 6.2.0 which don't exist in 6.1.2. So it's not clear if the linker would even accept the other version. I don't know enough about sonames to be able to answer that.

**Comment by fingolfin** [comment]
These are not sonames, they are libtool `version-info` triplets, `current:revision:age`. You perhaps got them from the GMP `Makefile.am`; the third column is for the C++ interface, which (I think?) is not relevant for Flint. So these are the relevant values (an excerpt from the full list):
```
...
5.1.0   11:0:1
5.1.1   11:1:1
5.1.2   11:2:1
6.0.0   12:0:2
6.1.0   13:0:3
6.1.1   13:1:3
6.1.2   13:2:3
6.2.0   14:0:4
```
To compute the version part of the soname (i.e. the `NNN` in `libgmp.so.NNN`) on Linux from, take the difference between the first and third value in the version-info triplet. You'll observe that for all the above, that's 10. Indeed, it has been that since GMP 5.0.1 (it wasn't in 5.0.0 due to a bug). So all these versions are "upwards compatible", meaning that one can use a program which was compiled against an old version with any of the newer ones. (Of course only as long as it restricts itself to documented public APIs, so code directly working with the internals of an `mpz_t` can be tripped up, as happened to Flint when they introduced lazily allocated `mpz_t` values). 

Now, they indeed incremented the `current` value from 13 to 14, which should mean that new interfaces were added. But that only matters if you actually use those new interfaces, but of course you don't. Out of curiosity, I diff'ed `gmp.h` from 6.1.2 to 6.2.0 -- the single new interfaces is `mpn_gcd_11` (which is not even documented).

So, really, as long as Flint always correctly deals with lazily allocated `mpz_t` values, all is well.

**Comment by wbhart** [comment]
Ok. No wonder this soname thing has been confusing me.

**Comment by tthsqe12** [comment]
reopened because the cxx wrapped stuff is not done yet?

**Comment by thofma** [comment]
Yes.
