### ISSUE TITLE
Getting rid of deps/build.jl or at least minimize what it does.

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Singular.jl#268]
The `deps/build.jl` currently still does two things:
1. it generates some shell/julia hybrid scripts for 4ti2 support (but see also issue #236)
2. it calls `parselibs.jl` to generate `src/libraryfuncdictionary.jl`

Note that the output of 1. is independent of the Julia version; and in principle, we could put these scripts into `Singular_jll`. Alternatively, we could generate these scripts at startup; this might be useful for dealing with issue #236 anyway (namely then we could insert into the scripts actual full paths, alleviating the need 

For 2., actually the data in `src/libraryfuncdictionary.jl`  might change whenever Singular_jll is updated. Unfortunately it takes 1-2 seconds to run for me, so moving it to the `Singular.jl` startup doesn't seem practical. However, perhaps  it would make sense to move this to `libsingular_julia_jll`, i.e., generate `libraryfuncdictionary.jl` as part of the build process of that JLL?

**Comment by benlorenz** [comment]
Regarding 2:
In Polymake.jl we generate (via a command from `libpolymake_julia_jll`) several json files describing the available functions and at the end `@eval` the result. The files are created [here](https://github.com/oscar-system/Polymake.jl/blob/d74e9651c823031fa5c6d6459665256e9369e91b/src/Polymake.jl#L82) and julia code is generated [here](https://github.com/oscar-system/Polymake.jl/blob/master/src/generate_applications.jl) (and via [this](https://github.com/oscar-system/Polymake.jl/blob/master/src/meta.jl) rather long file).

This is in the global scope and thus only done during precompilation, i.e. it only adds overhead during the first load (or when dependencies are updated).

In our case doing this during the build process was not an option as we cannot run polymake in the cross compilation environment.
