### ISSUE TITLE
Incompatible library version: libfactory.dylib requires version 15.0.0 or later, but libgmp.dylib provides version 14.0.0

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/Singular.jl#271]
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> up
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Installed Singular_jll ─ v4.1.3+4
Downloading artifact: Singular
No Changes to `~/.julia/environments/v1.5/Project.toml`
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [43d676ae] ↑ Singular_jll v4.1.3+3 ⇒ v4.1.3+4

(@v1.5) pkg> build Singular
   Building LoadFlint → `~/.julia/packages/LoadFlint/10o48/deps/build.log`
   Building Nemo ─────→ `~/.julia/packages/Nemo/NVxdo/deps/build.log`
   Building Singular ─→ `~/.julia/packages/Singular/cuKCT/deps/build.log`
┌ Error: Error building `Singular`:
│ ERROR: LoadError: InitError: could not load library "~/.julia/artifacts/10c07259a7c1c520ee1684af6942e4a22334f893/lib/libfactory.dylib"
│ dlopen(~/.julia/artifacts/10c07259a7c1c520ee1684af6942e4a22334f893/lib/libfactory.dylib, 1): Library not loaded: @rpath/libgmp.10.dylib
│   Referenced from: ~/.julia/artifacts/10c07259a7c1c520ee1684af6942e4a22334f893/lib/libfactory-4.1.3.dylib
│   Reason: Incompatible library version: libfactory.dylib requires version 15.0.0 or later, but libgmp.dylib provides version 14.0.0
│ Stacktrace:
│  [1] dlopen(::String, ::UInt32; throw_error::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
│  [2] dlopen(::String, ::UInt32) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
│  [3] __init__() at ~/.julia/packages/Singular_jll/2anIT/src/wrappers/x86_64-apple-darwin14-cxx11.jl:170
│  [4] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
│  [5] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:782
│  [6] _require(::Base.PkgId) at ./loading.jl:1007
│  [7] require(::Base.PkgId) at ./loading.jl:928
│  [8] require(::Module, ::Symbol) at ./loading.jl:923
│  [9] include(::String) at ./client.jl:457
│  [10] top-level scope at none:5
│ during initialization of module Singular_jll
│ in expression starting at ~/.julia/packages/Singular/cuKCT/deps/build.jl:3
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949

(@v1.5) pkg>
```

**Comment by giordano** [comment]
@mohamed-barakat would you be able to checkout this branch of the General registry https://github.com/JuliaRegistries/General/pull/21627?  I'm confident that this should work (in the sense that you'll get a working revision, but it'll be the previous version of the `Singular` library), but I'd like to double check with you.

**Comment by mohamed-barakat** [comment]
Simply dev'ing `Singular_jll` worked:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> dev Singular_jll
    Cloning git-repo `https://github.com/JuliaBinaryWrappers/Singular_jll.jl.git`
  Resolving package versions...
Updating `~/.julia/environments/v1.5/Project.toml`
  [43d676ae] + Singular_jll v4.1.3+5 `~/.julia/dev/Singular_jll`
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [43d676ae] ~ Singular_jll v4.1.3+4 ⇒ v4.1.3+5 `~/.julia/dev/Singular_jll`


(@v1.5) pkg> build Singular
   Building LoadFlint → `~/.julia/packages/LoadFlint/10o48/deps/build.log`
   Building Nemo ─────→ `~/.julia/packages/Nemo/NVxdo/deps/build.log`
   Building Singular ─→ `~/.julia/packages/Singular/cuKCT/deps/build.log`

(@v1.5) pkg>
```

**Comment by mohamed-barakat** [comment]
Thank you very much.

**Comment by mohamed-barakat** [comment]
But now I again run into https://github.com/oscar-system/Singular.jl/issues/270.

**Comment by giordano** [comment]
> (in the sense that you'll get a working revision, but it'll be the previous version of the Singular library)

**Comment by fingolfin** [comment]
There is another issue here, though: GMP 6.1.2 and 6.2.0 *are* binary compatible in that 6.2 only adds APIs (in a minor way). This is definitely reflected by the soname version on Linux. But perhaps it is "broken" on macOS (typing this on a phone so forgive me for not delving into the nuances here). So something is off here. But I am pretty confident we can resolve this (eg fix 6.2 compat version, and also force building the JLL against 6.1.2; added complication being that Yggdrasil now uses Julia 1.6...). But it's weekend and these days unfortunately I can GWT in front of my computer on weekends is late at night (and only if I don't fall asleep Reading bedtime stories).

**Comment by giordano** [comment]
> This is definitely reflected by the soname version on Linux. But perhaps it is "broken" on macOS (typing this on a phone so forgive me for not delving into the nuances here).

Also the macOS library has the same soversion as GMP v6.1, but libraries on macOS have an additional "compatibility version": GMP v6.1 has compatibility version 14, GMP v6.2 has compatibility version v15.

Compatibility of binaries is an ungodly mess.  The most frustrating part is that it's totally unpredictable.

**Comment by fingolfin** [comment]
Actually I have a fairly good idea how to resolve this, this is my "home turf": I am a macOS expert and have dealt with Issues like this for the past 20 years. But that was before I had kids😂

**Comment by mohamed-barakat** [comment]
No hassle, `Singular.jl` is now working again on Mac OS and I can wait a couple of days for a proper solution. Enjoy your kids.

**Comment by giordano** [comment]
There is a more general issue about JLLs involving binaries that are dependencies of Julia: https://github.com/JuliaPackaging/Yggdrasil/issues/1682.  @fingolfin you may want to chime in :slightly_smiling_face:
