### ISSUE TITLE
Custom orderings for polynomial rings

### ISSUE THREAD

**Issue by alexej-jordan** [oscar-system/Singular.jl#273]
I want to execute the following `Singular` command in `Singular.jl`:
```
ring R = 0, (w1,w2,x1,x2,x3), (lp(2), Wp(1,5,2));
```
I know how to translate the majority of this command resulting in
```julia
R, vars = Singular.PolynomialRing(QQ, ["w1", "w2", "x1", "x2", "x3"]; ordering=:lex)
```
Now, the ordering is still not correct. The docs state that there are several `Symbol`s which can be given, but these do not cover this case. Is it right to assume that the corresponding support is not contained in `Singular.jl` (yet)?

**Comment by wbhart** [comment]
That is correct at this point in time.

We may need to support *construction* of polynomials with this ordering in MPoly.jl in AbstractAlgebra.jl to make this possible. This is feasible, but not there currently.

**Comment by alexej-jordan** [comment]
Thank you for your response

**Comment by fieker** [comment]
On Wed, Sep 23, 2020 at 04:39:27PM -0700, alexej-jordan wrote:
> Closed #273.

Actually, it depends on what you want to do. In Oscar.jl it is possible
to take any MPoly, and get the leading coeff and iterate the monomials
wrt any weigt ordering.

**Comment by fieker** [comment]
The core question is: what do you want to compute? In Oscar there might be a non-singular way of achieving what you want...
We already support (looking at the code)
  coeffs, exponent_vectors, monomials, terms, leading_(term,coeff,monomial,ideal) wrt to any ordering, including random weights
However, the ring with this ordering we do not have.

**Comment by tthsqe12** [comment]
@alexej-jordan @fieker Can we close this again? The singular.jl solution is here https://oscar-system.github.io/Singular.jl/latest/polynomial/#Term-orderings
