### ISSUE TITLE
crt is broken

### ISSUE THREAD

**Issue by rfourquet** [oscar-system/Singular.jl#281]
```julia
julia> crt(ZZ(2), ZZ(3), ZZ(4), ZZ(5))
type parCxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.coeffs}
type rVector{CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.number}}
type mVector{CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.number}}
Got through
0

julia> import Nemo

julia> crt(Nemo.ZZ(2), Nemo.ZZ(3), Nemo.ZZ(4), Nemo.ZZ(5))
14
```

I gave up after trying to fix that for one hour. If no-one knows how to get `libSingular.n_ChineseRemainderSym` working, we should either delete/hide the current buggy version, or implement it by converting first the arguments to `Nemo.fmpz`.

**Comment by wbhart** [comment]
@hannes14 should be able to help fix this.

**Comment by fingolfin** [comment]
@hannes14 what is the status of this? have you had a look at it?

**Comment by fieker** [comment]
If I had to hazard a guess: wrong input. In Singular, crt is done on coefficients of polynomials, hence, I'd expect the input to be 2 polys and 2 ints...

**Comment by fingolfin** [comment]
This still occurs. @hannes14 @tthsqe12 can you please have a look?
