### ISSUE TITLE
Factorization bug (?)

### ISSUE THREAD

**Issue by pogudingleb** [oscar-system/Singular.jl#294]
Good morning/afternoon!

The following code

```julia
using Singular

R, (b, y1, y2, r) = PolynomialRing(QQ, ["b", "y1", "y2", "r"])

q = -36 + 12 * b - b^2 + b^2 * r^2 + 36 * b^2 * y1^2 - 12 * b^3 * y1^2 + b^4 * y1^2
r = -36 - 12 * b - b^2 + b^2 * r^2 + 36 * b^2 * y1^2 + 12 * b^3 * y1^2 + b^4 * y1^2

println(factor(q * r))

println(factor_squarefree(q * r))
```

prints the product (unfactored) for both `println`'s. 
I am using Julia 1.5.2, Singular.jl 0.4.1. 
I wonder whether this is the expected behavior.

Thank you in advance!

Best regards,
Gleb

UPD: Tried the same polynomials in SageMath (v9.1) which shoul use Singular. Everything was fine.

```python
R.<b, y1, y2, r> = PolynomialRing(QQ, ["b", "y1", "y2", "r"])
q = -36 + 12 * b - b^2 + b^2 * r^2 + 36 * b^2 * y1^2 - 12 * b^3 * y1^2 + b^4 * y1^2
r = -36 - 12 * b - b^2 + b^2 * r^2 + 36 * b^2 * y1^2 + 12 * b^3 * y1^2 + b^4 * y1^2
p = q * r
p.factor()
```

**Comment by fingolfin** [comment]
@hannes14 @tthsqe12 can you please take a look at this?

**Comment by tthsqe12** [comment]
Can confirm: println(factor(q * r)) takes a long time to report the (wrong) answer. This is probably a bug in the ntl-less singular.
I have just opened a pr https://github.com/wbhart/flint2/pull/852 which essentially finishes factoring (modulo the inevitable bug fixes and performance tunings).
