### ISSUE TITLE
double definition

### ISSUE THREAD

**Issue by fieker** [oscar-system/Singular.jl#308]
julia> using Revise, Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
..
WARNING: Method definition convert(Type{Nemo.fmpz}, Singular.n_Z) in module Singular at /home/fieker/.julia/dev/Singular/src/number/n_Z.jl:375 overwritten in module Oscar at /home/fieker/.julia/dev/Oscar/src/Rings/mpoly.jl:190.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition convert(Type{Nemo.fmpq}, Singular.n_Q) in module Singular at /home/fieker/.julia/dev/Singular/src/number/n_Q.jl:346 overwritten in module Oscar at /home/fieker/.julia/dev/Oscar/src/Rings/mpoly.jl:194.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Any(Singular.n_Q) in module Singular at /home/fieker/.julia/dev/Singular/src/number/n_Q.jl:347 overwritten in module Oscar at /home/fieker/.julia/dev/Oscar/src/Rings/mpoly.jl:198.
  ** incremental compilation may be fatally broken for this module **

those were recently added to Singular (where they possibly belong), but this wreaks havoc with the already existing stuff in Oscar.

**Comment by rfourquet** [comment]
I don't know of a good way of fixing that (and I asked on Julia's slack, without getting a solution). I can think of either:
1. release a new Singular version, and make Oscar depend on it (and make it require this latest Singular.jl release)
2. define a `Singular.version()` function, like in `Nemo`. Then we can guard these pirate definitions in Oscar within a Singular version check (`if isdefined(Singular, :version) && Singular.version() >= "v"0.4.2.0-dev" ...`).

Solution 2) might be overkill, depending on whether we think version checks will be useful in other instances. I don't understand why there is no support from `Pkg` for package version checks...

**Comment by fieker** [comment]
On Wed, Dec 09, 2020 at 04:06:48AM -0800, Rafael Fourquet wrote:
> I don't know of a good way of fixing that (and I asked on Julia's slack, without getting a solution). I can think of either:
> 1. release a new Singular version, and make Oscar depend on it (and make it require this latest Singular.jl release)
We're working on this. Probably have a release later today.
> 2. define a `Singular.version()` function, like in `Nemo`. Then we can guard these pirate definitions in Oscar within a Singular version check (`if isdefined(Singular, :version) && Singular.version() >= "v"0.4.2.0-dev" ...`).
Singular.VERSION_NUMBER
> 
> Solution 2) might be overkill, depending on whether we think version checks will be useful in other instances. I don't understand why there is no support from `Pkg` for package version checks...
The julia dev are deliberately against. You should state what you need
and let julia worry about it.

**Comment by rfourquet** [comment]
Ok then! Let me know if I can help with something.

**Comment by fingolfin** [comment]
I think this has been resolved already with the Singular.jl 0.4.2 release? @fieker?
