### ISSUE TITLE
Module types

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#34]
We currently have just smodule for the old Singular modules. But these are used variously in Singular for both kernel and quotient modules.

We should distinguish these in Singular.jl and also distinguish them from the new subquotient modules that Janko has been implementing.

We need to make a decision on names and discuss which operations should return which kind of module, and generally design an interface that makes it easy to work with these things.

**Comment by fingolfin** [comment]
I don't think this is what we our plan is these days. `smodule` is low level and in Singular.jl; in Oscar.jl we do distinguish these things, though.
