### ISSUE TITLE
Libraries are missing, e.g. dmodideal.lib

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#378]
I don't know why, but dmodideal.lib is missing. This is a PLURAL library, but for example dmod.lib or dmodapp.lib are also and they are contained. Any idea why this library could be missing? @hannes14 @tthsqe12

P.S.: At the moment we are using the binaries from here: https://github.com/JuliaBinaryWrappers/Singular_jll.jl/releases/tag/Singular-v402.0.101%2B0

CC: @johannes-hoffmann

**Comment by thofma** [comment]
P.S.: This is our build script https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/Singular/build_tarballs.jl.

**Comment by fingolfin** [comment]
Sounds like it might be a bug in the `make install` target of Singular, which does not install those -- likely a matter of adding those files to the right `*_DIST` Makefile variables

**Comment by fingolfin** [comment]
Maybe @hannes14 has some insights?

**Comment by tthsqe12** [comment]
This file has all of the other dmod stuff but no dmodideal
https://github.com/Singular/Singular/blob/spielwiese/Singular/singular-libs

**Comment by hannes14** [comment]
fixed with https://github.com/Singular/Singular/commit/944ec187afb4771589952c938c050b0c3f99217b

**Comment by thofma** [comment]
Singular tests are failing according to CI for https://github.com/Singular/Singular/commit/944ec187afb4771589952c938c050b0c3f99217b.

Which commit should we use?

**Comment by hannes14** [comment]
0a3a24882d6675f96135dd79796fcea48770e901

**Comment by thofma** [comment]
Fixed by #380
