### ISSUE TITLE
ngens vs nvars

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#40]
In AbstractAlgebra/Nemo we use nvars for the number of variables of a multivariate poly. But currently we have ngens in Singular.jl.

**Comment by fieker** [comment]
On Thu, Jun 07, 2018 at 04:15:30PM +0000, wbhart wrote:
> In AbstractAlgebra/Nemo we use nvars for the number of variables of a multivariate poly. But currently we have ngens in Singular.jl.
> 

I think all should use ngens: this also covers algebras, groups,
modules.
nvars only applies to poly rings.

At least ngens should be available for all, if you want more specialized
names in other situations as well: fine. ngens covers everything...

Claus

**Comment by wbhart** [comment]
I think the reason nvars was used in Singular.jl is that it is meaningful to ask how many variables an ideal is in. This is independent of how many generators it has as an ideal.

I lean towards having both nvars and ngens available where it is meaningful. But ngens should only be available when the representation of the object is described in terms of generators. It's obviously meaningless to talk about the number of generators, even of a finitely generated ideal in general. You can only ask about the number of generators in a given representation.

Computing a minimum basis number could get quite hairy, especially in the non-commutative case.

**Comment by fieker** [comment]
On Fri, Jun 08, 2018 at 04:51:56AM -0700, wbhart wrote:
> I think the reason nvars was used in Singular.jl is that it is
> meaningful to ask how many variables an ideal is in. This is
> independent of how many generators it has as an ideal.
I would differ: the natural question is about the nvars of the ring the
ideal is in, not about the ideal. I think this is mainly convenience. I
guess at this point I'd not do ngens nor nvars for ideals. Thinking
about the number fields: degree for an ideal e.g. is different than the
degree of the ring or field the ideal is in.
Possibly this needs to be carefully separated.
> 
> I lean towards having both nvars and ngens available where it is
> meaningful. But ngens should only be available when the representation
> of the object is described in terms of generators. It's obviously
> meaningless to talk about the number of generators, even of a finitely
> generated ideal in general. You can only ask about the number of
> generators in a given representation.
This agrees with not having either for ideals.
> 
> Computing a minimum basis number could get quite hairy, especially in the non-commutative case.
Yep.

**Comment by fieker** [comment]
On Fri, Jun 08, 2018 at 07:26:35AM -0700, wbhart wrote:
> Knowing the number of generators in an ideal is currently indispensable. It
> needs to be defined in order for manipulation of the ideal to be possible.
It's a question of style and consistency. If ideals are (primarily)
rings, this holds and nvars is fine. If they are (primarily) elements of
the ideal set, then nvars applies to the ring, not to the ideal.
> 
> I understand the argument, but this is just a matter of practicality. If it
> isn't there today, it will be as soon as the first person that needs it
> comes along (in fact that already happened).
> 
Practicality vs. correctness... I would never ask for the variables in
the ideal - especially as this will give the number for the ring. Most
ideals will not actually contain any variables...

ngens for ideals as ideals is tricky, and possibly should be banned. As
modules it should be the number of generates currently used, ie. the
number used to define the module.

Maybe rank would be less controversial? All names, especially all
generic sounding names need to be totally predictable across the system
and all areas. Exceptions for one area are extremely bad. (My opinion).
Similar the maximalideal discussion: to have this as a shortcut for
powers is indefensible. This will only result in pain and tears in the
long run...

Maybe "all" the "major" players should meet and discuss some interfacing
problems away and independently of algorithms and programming style?
Focussing on mathematics?

**Comment by hannes14** [comment]
I consider ideals a special case of modules, so ngens (the number of generates currently used)
is applicable also here.
nvars should refer to a polynomial ring.
But how to name the function returning the number of variables occuring in an ideal of a polynomial
ring (for example, to decide if it can be mapped to polynomial ring with less variables)

**Comment by fieker** [comment]
On Fri, Jun 08, 2018 at 08:27:48AM -0700, Hans Schoenemann wrote:
> I consider ideals a special case of modules, so ngens (the number of generates currently used)
> is applicable also here.
> nvars should refer to a polynomial ring.
> But how to name the function returning the number of variables occuring in an ideal of a polynomial
> ring (for example, to decide if it can be mapped to polynomial ring with less variables)
All ideals need to contain all variables. However, you're asking if the
generators can be mapped to a smaller ring - which is different.
I'd not define nvars for an ideal, nor a polynomial.
For a sequence/set of mpolys I'd envision a function support or
used_variables or similar that actually also returns the variables
actually used. Possibly even a smaller ring and the map to the smaller
ring.
But not nvars/ ngens...

**Comment by wbhart** [comment]
Fixed in master.
