### ISSUE TITLE
factorization over extension fields

### ISSUE THREAD

**Issue by 8d1h** [oscar-system/Singular.jl#409]
Hi! I noticed that currently Singular.jl only handles factorization over QQ, ZZ, prime fields and function fields over prime fields. Is there support for factorization over extension fields like `FiniteField(2,2,"a")`? Or maybe an easy way to convert the polynomial and let it handled by Flint? Thanks!

---

A longer story: actually I'm trying to implement a function to solve a system of polynomials (i.e. to enumerate the rational points on a variety). It seems that right now Magma is the only choice for doing this. None of the existing functionalities in Macaulay2, Sage, or Singular is competitive at all. I've tried implementing a quite simple elimination algorithm in all three, which vastly improved the speed but is still a lot slower than Magma.

Then I discovered Julia and I found out that this Singular wrapper runs faster than Singular itself! In particular the elimination algorithm now runs faster than Magma in some cases! (although it doesn't work yet for extension fields) I'd love to make this available. So it would be nice if someone could tell me how to contribute to the project. Maybe this should go into Oscar.jl?

**Comment by tthsqe12** [comment]
> I noticed that currently Singular.jl only handles factorization over QQ, ZZ, prime fields and function fields over prime fields. Is there support for factorization over extension fields like FiniteField(2,2,"a")

I will look into this and get back asap. We may or may not have a julia factor function that calls singular's factor function. Do you need it just for univariates?

> I'd love to make this available. So it would be nice if someone could tell me how to contribute to the project. Maybe this should go into Oscar.jl

Yeah, Oscar.jl is probably the place for this. Singular.jl is really just meant to be a wrapper of singular and it's libraries.

**Comment by 8d1h** [comment]
> I will look into this and get back asap. We may or may not have a julia factor function that calls singular's factor function. Do you need it just for univariates?

Thanks! Yes for this application univariates will suffice.

**Comment by fieker** [comment]
We have in Oscar factoring of univariates over all finite fields, all finite extensinos of Q as well as of multivariates over Q and number fields and absolute factoring (so far)....

**Comment by 8d1h** [comment]
> We have in Oscar factoring of univariates over all finite fields, all finite extensinos of Q as well as of multivariates over Q and number fields and absolute factoring (so far)....

Yes you are right. I just checked out factoring in Oscar and it works out of the box!

However, the version in Oscar runs 4 or 5 times slower than the Singular.jl version and uses a lot more memory (my code is probably far from optimal yet, but I kept the two versions almost identical).

I have the code here: [Singular.jl version](https://github.com/8d1h/RationalPoints/blob/master/rational_points.jl) and [Oscar version](https://github.com/8d1h/RationalPoints/blob/master/rational_points_oscar.jl). There is an example `example()`, which runs in 1 second in Singular.jl but 4 or 5s in Oscar (also you can bump up the scale by using `example(32003)` which uses a larger characteristic, and the difference in speed becomes more apparent).

**Comment by tthsqe12** [comment]
I am surprised the oscar version is only 4x slower.
Here are some thing you can do to bring it closer in execution to the singular version:

--------------------------------------

```julia
function example(char=7823)
    R,(x,y,z,w) = PolynomialRing(FiniteField(char,1,"a")[1],["x","y","z","w"])
```
First of all FiniteField(char,1,"a")[1] is a generic finite field constructor for any degree and characteristic. To be equivalent to singular's `Fp(char)`, you could use something like 
```julia
    R,(x,y,z,w) = PolynomialRing(GF(char),["x","y","z","w"])
```

-------------------------------------
```julia
# list the elements of a finite field
function get_elements(F)
    char = Int(characteristic(F))
    a = gen(F)
    d = degree(F)
    vcat([F(0)], [a^i for i in 0:char^d-2])
end

Second of all, the generator returned by `gen(F)` is not guaranteed to be a generator of F^*. This is much simpler and safer:

```julia
function get_elements(F)
    collect(F)
end
```

If `collect(F)` doesn't work for the singular version, it can be added.

-------------------------
```julia
function enum!(I, part, els, ans)
    R = base_ring(I)
    char = characteristic(R)
    F = base_ring(R)
....
    if elim == 0
        values = els
    else
        values = get_zeros(elim)
    end
...
```

Finally, You have this big function `get_zeros` to compute the zeros of an spoly that happens to be univariate in some variable. In oscar there should be roots function which does this - the only problem is that you have to feed it a real univariate polynomial.
I would make a little helper
```julia
function to_univar(a, var::Int, Kx)
  r = zero(Kx)
  for (c, ev) in zip(coefficients(a), exponent_vectors(a))
    setcoeff!(r, ev[var], c)
  end
  return r
end
```
and then do
```
       values = roots(to_univar(elim, i +1, F["x"][1]))
```

**Comment by thofma** [comment]
You can just do
```julia
    to_univariate(F["x"][1], elim)
```

**Comment by 8d1h** [comment]
Wow thanks a lot for the detailed comments! Now the Oscar version runs pretty fast too! :)

**Comment by tthsqe12** [comment]
@thofma That almost always works, but the code has a bug in it:
```julia
julia> using Oscar

julia> R,(x,y)=PolynomialRing(GF(13), ["x", "y"])
(Multivariate Polynomial Ring in x, y over Galois field with characteristic 13, gfp_mpoly[x, y])

julia> to_univariate(GF(13)["t"][1], x+1)
t + 1

julia> to_univariate(GF(13)["t"][1], R(1))
ERROR: MethodError: Cannot `convert` an object of type Ptr{Nothing} to an object of type Singular.libSingular.ideal

Stacktrace:
 [1] cxxconvert(to_type::Type{CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.ideal}}, x::Ptr{Nothing}, #unused#::Type{CxxWrap.CxxWrapCore.IsCxxType})
   @ CxxWrap.CxxWrapCore ~/.julia/packages/CxxWrap/OcN1Z/src/CxxWrap.jl:581
 [2] cconvert(to_type::Type{CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.ideal}}, x::Ptr{Nothing})
   @ CxxWrap.CxxWrapCore ~/.julia/packages/CxxWrap/OcN1Z/src/CxxWrap.jl:564
 [3] getindex(arg1::Ptr{Nothing}, arg2::Int64)
   @ Singular.libSingular ~/.julia/packages/CxxWrap/OcN1Z/src/CxxWrap.jl:618
 [4] to_univariate(R::GFPPolyRing, p::gfp_mpoly)
   @ AbstractAlgebra.Generic ~/.julia/dev/AbstractAlgebra/src/generic/MPoly.jl:4447
 [5] top-level scope
````

--------------------------------------

as for this
```julia
# this doesn't work right now
function exampleGF()
    R,(x,y) = PolynomialRing(FiniteField(19,3,"a")[1],["x","y"])
    I = Ideal(R,y^27-x^8*(1-x))
    @time length(points(I))
end
```

I was finding this hard to believe, but yes, in fact the singular kernel does not have factoring over the zech log representation implemented (it should though). This is online (real) singular:

```
                     SINGULAR  
 A Computer Algebra System for Polynomial Computations       /   version 4.1.3
                                                           0<
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \   Mar 2020
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> ring r = (19^3,a),(x,y),dp;
> factorize(x^3-a^3);
   ? not implemented
   ? error occurred in or before STDIN line 2: `factorize(x^3-a^3);`
> 
```

----------------

I just put algebraic extensions into Singular.jl, so I will make sure the factorzation work over them. This should then match the features of the real singular. However, factoring over the zech log representation will require kernel intervention and might take longer (if it is even possible).

**Comment by 8d1h** [comment]
> I just put algebraic extensions into Singular.jl, so I will make sure the factorzation work over them. This should then match the features of the real singular. However, factoring over the zech log representation will require kernel intervention and might take longer (if it is even possible).

Thanks that will be great!

(Actually I didn't know that finite fields can be represented this way in Singular: I was surprised when I found out that all elements are `a^i`, which is why I wrote `get_elements` like that; normally I would just enumerate all the polynomials.)

**Comment by tthsqe12** [comment]
@8d1h Here is an update on how this will look hopefully in the next release. If you have any objections, speak now. I think `Fp` is going to have to be deprecated and replaced by `GF`: does everything else look good?
```
julia> using Singular

julia> Qa, (a,) = FunctionField(QQ, ["a"])
(Function Field over Rational Field with transcendence basis n_transExt[a], n_transExt[a])

julia> K, a = AlgebraicExtensionField(Qa, a^2+1)
(Algebraic Extension of Rational Field with defining equation a^2 + 1, a)

julia> R, (x, y, z) = PolynomialRing(K, ["x", "y", "z"])
(Singular Polynomial Ring (0,a),(x,y,z),(dp(3),C), spoly{n_algExt}[x, y, z])

julia> factor(x^4+y^4*z^4)
1 * (y^2*z^2 - a*x^2) * (y^2*z^2 + a*x^2)

julia> F7a, (a,) = FunctionField(Fp(7), ["a"])
(Function Field over Finite Field of Characteristic 7 with transcendence basis n_transExt[a], n_transExt[a])

julia> K, a = AlgebraicExtensionField(F7a, a^2+1)
(Algebraic Extension of Finite Field of Characteristic 7 with defining equation a^2 + 1, a)

julia> R, (x, y, z) = PolynomialRing(K, ["x", "y", "z"])
(Singular Polynomial Ring (7,a),(x,y,z),(dp(3),C), spoly{n_algExt}[x, y, z])

julia> factor(x^4+y^4*z^4)
1 * (y*z + (2*a + 2)*x) * (y*z + (2*a - 2)*x) * (y*z + (-2*a + 2)*x) * (y*z + (-2*a - 2)*x)
```

**Comment by 8d1h** [comment]
Thanks that looks great!
