### ISSUE TITLE
bug in `reduce`

### ISSUE THREAD

**Issue by 8d1h** [oscar-system/Singular.jl#416]
Hi! The `reduce` function silently produces wrong result when the coefficient ring is non-standard. Here is a minimal example.
```julia
julia> R,(x,y) = PolynomialRing(QQ["a"][1],["x","y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_unknown{AbstractAlgebra.Generic.Poly{n_Q}}}[x, y])

julia> reduce(x^2+y^2,std(Ideal(R,x-y^2)))
-x^2 - x
```
The result is correct if we take the coefficient ring to be `QQ` or `FunctionField(QQ,["a"])[1]`. (In fact I was using `simplify` in Oscar and I got inconsistent results.)

**Comment by tthsqe12** [comment]
Wow, that is a fun one: Singular polynomial with coefficients as generic polys over Singular's rationals. :)

**Comment by 8d1h** [comment]
This doesn't work either.
```julia
julia> F,(a,) = PolynomialRing(QQ,["a"])
(Singular Polynomial Ring (QQ),(a),(dp(1),C), spoly{n_Q}[a])

julia> R,(x,y) = PolynomialRing(F,["x","y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_unknown{spoly{n_Q}}}[x, y])

julia> reduce(x^2+y^2,std(Ideal(R,x-y^2)))
-x^2 - x
```
I just wanted to introduce some parameters into the coefficients. I switch to `FunctionField` now so everything works fine. Still it would be nice if this could work, or maybe a warning should be given (I thought there were some integer overflows in my code or something...).

**Comment by tthsqe12** [comment]
Yup. Something bad is happening here, and it is not yet clear whom to blame. Will investigate fully tomorrow.

**Comment by tthsqe12** [comment]
This is a singular issue and will take some time to resolve.

**Comment by 8d1h** [comment]
What do you mean by singular issue? I think it works in singular.
```
                     SINGULAR                                 /  Development
 A Computer Algebra System for Polynomial Computations       /   version 4.2.0
                                                           0<
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \   Dec 2020
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \
> ring F = 0,(a),dp;
> ring R = F,(x,y),dp;
> ideal I = x-y2;
> reduce(x2+y2, std(I));
x2+x
```

**Comment by tthsqe12** [comment]
In your example, the `F` started out as the non-field `QQ[a]`. However, after it became the coefficient ring, it became the field `frac(QQ[a])` i.e. `QQ(a)`. The issue is with non-field inside the GB engine. I think the non-field circuits have only really ever been tested on `ZZ`. So, we are using singular in a new and untested way.

```
> ring F = 0,(a),dp;
> a+1/a;
a
> ring R = F, (x,y), dp;
> a+1/a;
(a2+1)/(a)
```

**Comment by 8d1h** [comment]
Well [this](https://www.singular.uni-kl.de/Manual/4-2-0/sing_28.htm) manual page seems to claim that at least `std` and `reduce` should work in this case...

**Comment by tthsqe12** [comment]
Sure, but I think Singular has only been tested with the two non-fields on the list, namely `ZZ` and `ZZ/mZZ`. Ring such as `QQ[a]`, where `1` is a perfectly reasonable answer to `gcd(6, 10)` and where `>` has no meaning, are in untested waters and present problems.

**Comment by 8d1h** [comment]
Ok I see. Thanks a lot for the explanation!

BTW is there going to be support for block orderings like `(dp(2),dp(3))` in singular.jl?

**Comment by tthsqe12** [comment]
I am working on the orderings this week.

**Comment by 8d1h** [comment]
Awesome! Thank you very much!

**Comment by thofma** [comment]
Should we be more picky about the rings we allow, e.g., throwing errors when using Gröbner basis functionality in untested waters? The results are obviously unreliable and it is very risky to expose to users. What do you think @tthsqe12?

**Comment by ederc** [comment]
I support @thofma's suggestion to not allow this kind of computation and throw an error. If we only state a warning and still deliver some possibly unreliable result, most users are not able to decide on their own if the result is valid or not.

**Comment by wdecker** [comment]
I support @thofma's  suggestion as well.

**Comment by tthsqe12** [comment]
This will entail throwing on any non-field ring that isn't Z or Z/nZ until singular's bugs are fixed.

**Comment by thofma** [comment]
I am not sure how many entry points there are where we would have to check this (excluding library calls). What do you think @tthsqe12?

**Comment by tthsqe12** [comment]
I am talking about simply throwing in the poly ring constructor. Simple and effective.

**Comment by thofma** [comment]
I see. This sounds like the easiest option. This would mean that on the Oscar side, creating ideals over such coefficient rings would throw an error? Fine with me, but would be good to hear if the other agree.

**Comment by wdecker** [comment]
Before we do that we should evaluate other options.

**Comment by thofma** [comment]
@ederc is looking into this.

**Comment by fingolfin** [comment]
The issue persists. Was there any progress here? @ederc ?

**Comment by ederc** [comment]
I don't see any solution for this issue in the near future. I still prefer @tthsqe12's suggestion to throwing in the poly ring constructor. At the moment we are not able to do any effective computation there.

@wdecker @hannes14: Any other thoughts or ideas?

**Comment by tthsqe12** [comment]
What if we know/assume the coefficient ring is Euclidean and has an effective divrem implemented?

**Comment by hannes14** [comment]
Am Tue, Nov 09, 2021 at 12:55:43PM -0800 schrieb ederc:
>    I don't see any solution for this issue in the near future. I still prefer
>    @tthsqe12's suggestion to throwing in the poly ring constructor. At the
>    moment we are not able to do any effective computation there.
> 
>    @wdecker @hannes14: Any other thoughts or ideas?
reduce for a ring with coefficients in Z (or Z/n) uses redtailBba_Z,
while general ring coeffs. uses redtailBba_Ring (which is untested in Singular).
redtailBba_Z uses n_IntMod, i.e. needs a divrem for the coefficients.
If we have divrem in all cases we shoulkd try to use redtailBba_Z
instead of redtailBba_Ring.

**Comment by thofma** [comment]
Does the following segfault provided by @YueRen the same underlying problem?
```julia
julia> QQs, s = Singular.Nemo.QQ["s"];

julia> w = [-1,2,0,2,0];

julia> R, (t, x1, x2, x3, x4) = PolynomialRing(QQs, ["t", "x1", "x2", "x3", "x4"], ordering = Singular.ordering_a([-1, 2, 0, 2, 0])*Singular.ordering_dp());

julia> rI = std(Singular.Ideal(R, [-t^2*x3 + 3*x2 + (s^2 + 1)*x4, s - t, x1 + (s + 1)*x3 - t*x2]));

julia> reduce(rI, rI)

signal (11): Segmentation fault: 11
in expression starting at REPL[6]:1
unknown function (ip: 0x0)
Allocations: 17581119 (Pool: 17574859; Big: 6260); GC: 19
```

**Comment by YueRen** [comment]
The crash above only occurs for the ordering `Singular.ordering_a([-1, 2, 0, 2, 0])*Singular.ordering_dp()`. The code runs with with the ordering `Singular.ordering_dp()`.

**Comment by YueRen** [comment]
I think I re-encountered the bug in the following example:

```
K,s = PolynomialRing(QQ,"s");
L = singular_coeff_ring(K);
R,(t,x1,x2,x3,x4) = Singular.PolynomialRing(L,["t","x1","x2","x3","x4"],ordering=Singular.ordering_a([-4,5,-3,5,-7])*Singular.ordering_dp());
s = L(s);

I = Singular.Ideal(R, [s - t, -t^2*x3 + 3*x2 + (s^2 + 1)*x4, x1 + (s + 1)*x3 - t*x2]);
I = Singular.std(I); # same as before

inJ = Singular.Ideal(R, [R(s), -t^2*x3 + 3*x2, x1 + (s + 1)*x3]);
inJred = Singular.reduce(inJ,I);
[lead-tail for (lead,tail) in zip(gens(inJ),gens(inJred))] # bug: some elements not in I
```

In the code above, the final array contains elements of the form `g - reduce(g|I)`, which should be contained in `I`. However, the second element is not, some of the signs are wrong.

**Comment by tthsqe12** [comment]
It seems that all the examples here are over a euclidean base ring. Given that Singular does GB over ZZ perfectly fine, how hard would it be to make sure arbitrary euclidean rings work?

**Comment by YueRen** [comment]
From a GB computation pov, there should be no systematic difference between ZZ and an arbitrary euclidean ring.

**Comment by fieker** [comment]
On Sun, Jul 31, 2022 at 04:34:55AM -0700, dan wrote:
> It seems that all the examples here are over a euclidean base ring. Given that Singular does GB over ZZ perfectly fine, how hard would it be to make sure arbitrary euclidean rings work?
> 
Arbitrarily?

**Comment by YueRen** [comment]
Just to check that I understand where the problem lies: The error is caused because of a bug in the untested `redtailBba_Ring` and @hannes14 suggests that we should be using `redtailBba_Z` instead which requires a `divrem` on the coefficients?

**Comment by tthsqe12** [comment]
So, I tried the following simplified example in Singular.jl. First of all,
Since divrem generically doesn't exist, the `fill_coeffs_with_function_data`
in libsingular-julia doesn't fill in an entry for `cfQuotRem`. This doesn't really
matter, though, because the only functions Singular calls related to division
are divisibility testing `DivBy` and gcd `Gcd`. I put print statements such as

```
function nemoRingDiv(a::Ptr{Cvoid}, b::Ptr{Cvoid}, cf::Ptr{Cvoid})
   n1 = julia(a)
   n2 = julia(b)
   n3 = Nemo.divexact(n1, n2)
@show (n1, " Div ", n2, " = ", n3)
   return number(n3)
end
```

and found that only `DivBy` and `Gcd` get called.

```
using Revise, Singular

R,(x,y) = PolynomialRing(Singular.Nemo.ZZ, ["x", "y"])
reduce(x^2+y^2,std(Ideal(R,x-y^2)))
```
producing
```
computing GB
(n1, " DivBy ", n2, " = ", n3) = (1, " DivBy ", -1, " = ", 1)
(n1, " DivBy ", n2, " = ", n3) = (1, " DivBy ", -1, " = ", 1)
(n1, " Gcd ", n2, " = ", n3) = (-1, " Gcd ", 1, " = ", 1)
-x^2 - x
```

**Comment by YueRen** [comment]
Interesting. Is the issue due to a differences in what Singular and Nemo expect from an exact division routine?

In an euclidean ring, I would've expected
``` 
n1 = (n1 div n2)*n2 + (n1 mod n2)
```
which does not the case above unless `1 mod -1 = 2`.

**Comment by tthsqe12** [comment]
In Nemo/AA `divrem(a,b)` should indeed be the same as `(div(a,b), mod(a,b))`, but this example proves that there are some errors in the singular kernel when it is not allowed to call a divrem function.
We probably should figure out when a Nemo.Ring is euclidean and fill in the relevent functions for singular, but I don't see a reason why the generic code should be forced to return wrong answers.

**Comment by YueRen** [comment]
@tthsqe12 Quick question: you mentioned that "this example proves that there are some errors in the singular kernel".

Does this mean:
(a) `Nemo.divexact` is working as intended in your example above (`Nemo.divexact(1, -1) == 1`),
(b) `Nemo.divexact` is not working as intended in your example above and it calls a Singular kernel function?

**Comment by tthsqe12** [comment]
Nemo.divexact is not being called. `DivBy` is divisibility testing, which return 1 for true and 0 for false.

**Comment by YueRen** [comment]
I see, I misunderstood your code. It does indeed look that everything is fine from the julia side.

**Comment by tthsqe12** [comment]
I don't think version 0.13.1 solves this problem. I still get
```
julia> R,(x,y) = PolynomialRing(Singular.Nemo.ZZ, ["x", "y"])
(Singular Polynomial Ring (Coeffs(18)),(x,y),(dp(2),C), spoly{Singular.n_RingElem{Singular.RingElemWrapper{Nemo.FlintIntegerRing, Nemo.fmpz}}}[x, y])

julia> reduce(x^2+y^2,std(Ideal(R,x-y^2)))
-x^2 - x
```

**Comment by YueRen** [comment]
@tthsqe12 Isn't that result correct? The leading monomial of `x-y^2` is `y^2` and eliminating it from `x^2+y^2` gives `(x^2+y^2)+(x-y^2)=x^2+x`. One can argue whether it is sensible that Singular multiplied the result by `-1`, but it is a valid result nonetheless.

**Comment by tthsqe12** [comment]
How is it valid to multiply the correct answer `x^2+x` by `-1`?

**Comment by YueRen** [comment]
Ah, right, nevermind. I got confused for a moment.

**Comment by fingolfin** [comment]
In Singular.jl 0.14 I get:
```
julia> R,(x,y) = PolynomialRing(QQ["a"][1],["x","y"])
(Singular Polynomial Ring (Coeffs(17)),(x,y),(dp(2),C), spoly{Singular.n_RingElem{AbstractAlgebra.Generic.Poly{n_Q}}}[x, y])

julia> reduce(x^2+y^2,std(Ideal(R,x-y^2)))
x^2 + x

```

and likewise

```
julia> F,(a,) = PolynomialRing(QQ,["a"])
(Singular Polynomial Ring (QQ),(a),(dp(1),C), spoly{n_Q}[a])

julia> R,(x,y) = PolynomialRing(F,["x","y"])
(Singular Polynomial Ring (Coeffs(18)),(x,y),(dp(2),C), spoly{Singular.n_RingElem{spoly{n_Q}}}[x, y])

julia> reduce(x^2+y^2,std(Ideal(R,x-y^2)))
x^2 + x
```

So does this mean the issue is resolved now?! But why and how?

**Comment by YueRen** [comment]
Maybe @hannes14 can comment on it and close the issue, he fixed the error in Singular a couple of months ago.

**Comment by fingolfin** [comment]
Ahh OK, so if there was a fix on the Singular side, that would of course explain it. My understanding from skimming the issue was that it was deemed to hard to fix

**Comment by hannes14** [comment]
Was fixed by https://github.com/Singular/Singular/commit/b97cce62f5eef441b51eed6f5c76a848e4c5183a
(introducing a parameter to distinguish reduce in GB computations from reduce in normal form computations).
It needed a new Singular_JLL to have effects in Singular.jl (which we have now with new Singular_JLL)
