### ISSUE TITLE
Bug for rationals

### ISSUE THREAD

**Issue by 8d1h** [oscar-system/Singular.jl#419]
Hi! I ran into a bug for rational numbers in Singular.jl.

At first I noticed that sometimes the rational number returned is not in reduced form.
```julia
julia> using Singular
Singular.jl, based on
                     SINGULAR                               /
 A Computer Algebra System for Polynomial Computations     /  Singular.jl: 0.5.2
                                                         0<   Singular   : 4.2.0p1
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann   \
FB Mathematik der Universitaet, D-67653 Kaiserslautern      \
     

julia> x = QQ(1//2)+QQ(3//2)
8/4
```
I thought at least the result is correct. But if one uses `numerator` on `x` twice, then funny things will happen.
```julia
julia> numerator(x)
2

julia> numerator(x) > 10^100000
true

julia> length(string(numerator(x)))
424828
```

**Comment by tthsqe12** [comment]
Yup. Can reproduce. This is bad.

**Comment by tthsqe12** [comment]
I think I have this under control now. The code in singular.jl is simply not correct, and there will be big changes in the next version.
Thanks for finding and reporting.

**Comment by 8d1h** [comment]
> I think I have this under control now. The code in singular.jl is simply not correct, and there will be big changes in the next version.
> Thanks for finding and reporting.

That's great! Glad I could help.

Also a small bug that probably don't deserve opening another issue for: the following
```julia
PolynomialRing(QQ, String[])
```
leads to a segfault, which I think could be easily avoided.

**Comment by 8d1h** [comment]
It seems that there are still occasions where a returned rational number is not reduced...
```julia
julia> R, (t,) = PolynomialRing(QQ, ["t"])
(Singular Polynomial Ring (QQ),(t),(dp(1),C), spoly{n_Q}[t])

julia> (QQ(1//2) + QQ(3//2)*t)(1)
8/4
```

**Comment by tthsqe12** [comment]
There is not much we can do about this apart from inventing a `reduce!` function and using it on all output from the singular kernel, which I am not keen on. As we now know, the arithmetic in the Singular kernel routinely generates unreduced fractions. You don't see these in the Singular language because they are reduced "when they get assigned somewhere", but we don't have this notion in julia.

**Comment by 8d1h** [comment]
I see, that's fairly reasonable, thanks for the explanation!

On the other hand, perhaps it's possible to change the `Base.show` function so that the printed out result is reduced? For example I think `spoly` are handled properly this way.
```julia
julia> f = t + (QQ(1,2)+QQ(3,2)*t)(1)
t + 2

julia> constant_coefficient(f)
8/4

julia> Singular.AbstractAlgebra.obj_to_string(f)
"t + 2"

julia> Singular.AbstractAlgebra.obj_to_string(constant_coefficient(f))
"2"
```

**Comment by tthsqe12** [comment]
Ok. I can have a look at the fraction printing.
