### ISSUE TITLE
The documentation for `lift` is wrong

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Singular.jl#452]
The current doc string for `lift` is

```
  lift(M::smodule, SM::smodule)

  represents the generators of SM in terms of the generators of M. Returns result, rest (Matrix(SM) =
  (Matrix(M)-Matrix(rest))*matrix(result)) If SM is in M, rest is the null module
```

Here are some calculations which clearly contradict the documentation. Am I missing something here @wdecker @hannes14 ?

```julia
julia> R,(x,y)=PolynomialRing(QQ,["x","y"]);

julia> lift(Singular.Module(R, vector(R, x)), Singular.Module(R, vector(R, x^2+1)))
(Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
0, Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x^2*gen(1)+gen(1))

julia> lift(Singular.Module(R, vector(R, x^2+1)), Singular.Module(R, vector(R, x^2)))
(Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
0, Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x^2*gen(1))
```

**Comment by tthsqe12** [comment]
So something definitely is going wrong here: I am not just mixing up the order of arguments.
```
julia> M = Singular.Module(R, vector(R, x))
Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x*gen(1)

julia> SM = Singular.Module(R, vector(R, x^2+1))
Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x^2*gen(1)+gen(1)

julia> result, rest = lift(M, SM)
(Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
0, Singular Module over Singular Polynomial Ring (QQ),(x,y),(dp(2),C), with Generators:
x^2*gen(1)+gen(1))

julia> Matrix(SM) == (Matrix(M)-Matrix(rest))*Matrix(result)
false
```

**Comment by fieker** [comment]
Have you tried to look where this is used in the graded modules? There
it gave "correct" results at least once.

**Comment by tthsqe12** [comment]
I have a suspicion that the doc string for `result, rest = lift(M::smodule, SM::smodule)` should be
`Matrix(SM) = Matrix(M)*matrix(result)) + Matrix(rest)`
with `rest = 0` if and only if `SM` is in `M`.

Now, in oscar, there is another issue. For example, `divides(a::MPolyQuoElem, b::MPolyQuoElem)`, which ignores `rest`, assumes that if `SM` is not in `M` then `result` is `zero`. This seems to be the current behaviour of singular, but I can't find it documented anywhere.

How I got into this: the `divrem` for singular.jl is broken (https://github.com/oscar-system/Singular.jl/pull/451), so I was looking into using the `lift` function with `result` as the quotient and `rest` and the remainder. However, this gives `x^2+1 = (0)*x + (x^2+1)`, which is not a very useful `divrem`. It looks like we need a new libsingualr_julia_jll with all of the option for idLift. sigh...

**Comment by tthsqe12** [comment]
@hannes14 could you add a correct doc string for both the lift functions? For the 5-argument version, it should state what the three boolean parameters mean, and it should state what the three outputs are/do.


https://github.com/oscar-system/Singular.jl/blob/dcecbba1afded4fa27d70479401aeb8decb206e5/src/module/module.jl#L293-L315

**Comment by hannes14** [comment]
see https://github.com/oscar-system/Singular.jl/pull/464
