### ISSUE TITLE
Broken promotions

### ISSUE THREAD

**Issue by 8d1h** [oscar-system/Singular.jl#459]
I updated Singular and some promotions are broken
https://github.com/8d1h/IntersectionTheory/runs/3060958843?check_suite_focus=true
```julia
julia> Singular.Nemo.QQ(1) * Singular.PolynomialRing(Singular.QQ, ["a"])[2][1]
ERROR: Cannot promote to common type
Stacktrace:
 [1] *(x::Nemo.fmpq, y::spoly{n_Q})
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/hlSYb/src/Rings.jl:83
```

I guess this is due to https://github.com/Nemocas/AbstractAlgebra.jl/pull/927

**Comment by thofma** [comment]
Thanks forbthe report. I will have a look.

**Comment by thofma** [comment]
Where do you need this? I am a bit hesitant to add it.

**Comment by 8d1h** [comment]
It's just for convenience (and it worked before...) I can always add it manually in my package.

Also coercion works already so it makes sense to allow promotion
```julia
julia> R = Singular.PolynomialRing(Singular.QQ, ["x"])[1];

julia> R(Singular.Nemo.QQ(1//2))
1//2
```

**Comment by thofma** [comment]
Yes, I understand. If we add a promote rule, it will be called automatically. For `fmpq` and `spoly{n_Q}` it is fine, but do you also want `fmpq` and `n_Q`? I am not sure want this, because it is not clear what the type of the result should be.

**Comment by 8d1h** [comment]
I agree. `fmpq` and `n_Q` should not be allowed. (I just saw the code for `spoly` promotion...)
