### ISSUE TITLE
Singular is still printing warnings

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#465]
```julia
julia> Qx, x = PolynomialRing(QQ, ["x1", "x2"])
(Singular Polynomial Ring (QQ),(x1,x2),(dp(2),C), spoly{n_Q}[x1, x2])

julia> M = Singular.Matrix(Qx, [1 0; 0 1])
[1, 0
0, 1]

julia> Singular.LibFinvar.invariant_ring(M, [1, 0, 0])
WARNING: In char 0, secondary_char0 should be faster
3-element Vector{smatrix{spoly{n_Q}}}:
 [x2, x1]
 [1]
 [0]
```

**Comment by tthsqe12** [comment]
Ok - the third element of the second argument is zero, so this should silence all extra printing, but
https://github.com/Singular/Singular/blob/spielwiese/Singular/LIB/finvar.lib#L6091
still comes out regardless of the value of `v`. @hannes14 should this warning be printed even when the user asked for no printing, or is this a bug in the algorithm selection?

**Comment by hannes14** [comment]
No bug in the algorithm selection, but missing tests for the verbosity level.
see https://github.com/Singular/Singular/commit/8ad2935b9f03ca7820942e4018d26497779d34e5

**Comment by tthsqe12** [comment]
This printing is no more.
