### ISSUE TITLE
Coefficient ring not working for fq_nmod/fq

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#467]
I was promised an `n_unkown`, but I get an error:
```julia
julia> F, = Singular.Nemo.FiniteField(2^61 - 1, 1, "a");

julia> CoefficientRing(F)
ERROR: InexactError: trunc(Int32, 2305843009213693951)
[...]
```

**Comment by tthsqe12** [comment]
I can remove the line of code that sets the characteristic. @hannes14 Is there something to which I can set the `cf->ch`, which is an `int`, so that Singular doesn't get confused here?

**Comment by hannes14** [comment]
Most uses of cf->ch are in the functions for the coefficients.
For all other cases, MAX_INT may be a good work-around.

**Comment by tthsqe12** [comment]
What about `-1`?

**Comment by hannes14** [comment]
Am Wed, Jul 21, 2021 at 07:57:31AM -0700 schrieb dan:
>    What about -1?
if cf-type>n_CF (the last in the enum type, n_unknown), this may work.

**Comment by tthsqe12** [comment]
ok
