### ISSUE TITLE
make the Singular functions diff and jacob be accessible from Julia

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#49]
It would be nice if the Singular functions `diff` (see https://www.singular.uni-kl.de/Manual/4-1-1/sing_230.htm) and `jacob` (see https://www.singular.uni-kl.de/Manual/4-1-1/sing_271.htm) would be accessible from Julia through Singular.jl. I would expect them to work analogously to the functions `derivation` and `jacobi` introduced in the following pull request to AbstractAlgebra.jl (though there `jacobi` is only implemented for a single polynomial as input).

https://github.com/Nemocas/AbstractAlgebra.jl/pull/102

I would suggest to use the names `derivative` and `jacobi` instead of `diff` and `jacob` on the Julia side.

**Comment by wbhart** [comment]
Merged. Please reopen if this doesn't satisfy the requirements.
