### ISSUE TITLE
isnegative in src/number/n_Zp.jl calls isless, which is not defined

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#50]
It seems that the function `isnegative(::Singular.n_Zp)` in `src/number/n_Zp.jl` calls `isless(::Singular.n_Zp, ::Singular.n_Zp)`, which is not defined.

I noticed this, because the function `show(io::IO, x::MPoly, U::Array{<: AbstractString, 1})` in `src/generic/MPoly.jl` in https://github.com/Nemocas/AbstractAlgebra.jl calls `isnegative`.

```
julia> using Singular

Welcome to AbstractAlgebra version 0.0.8

AbstractAlgebra comes with absolutely no warranty whatsoever


Welcome to Nemo version 0.8.4

Nemo comes with absolutely no warranty whatsoever


julia> K = Singular.N_ZpField(7)
Finite Field of Characteristic 7

julia> c = K(-1)
-1

julia> isnegative(c)
ERROR: MethodError: no method matching isless(::Singular.n_Zp, ::Singular.n_Zp)
Stacktrace:
 [1] isnegative(::Singular.n_Zp) at /home/florian/.julia/v0.6/Singular/src/number/n_Zp.jl:84
```

**Comment by fieker** [comment]
This should not be exposed/exist: Fp cannot be negative (or positive).
I think there is a functions testing if printing involves a leading - is
missing.

Claus

**Comment by sebasguts** [comment]
I think Claus is right. This `isnegative` should not exist at all.

Actually, in AbstractAlgebra it is defined to be `false` for `gfelem`s, which is still not ideal. If any, we should have a function which is called `hasminusinfront`.

**Comment by wbhart** [comment]
Yes, this function should certainly be renamed throughout the whole of
Oscar. And it should be defined for n_Zp's.

Thanks very much for the report. It is certainly a bug.
