### ISSUE TITLE
Singular is being noisy again

### ISSUE THREAD

**Issue by thofma** [oscar-system/Singular.jl#507]
Saw it on CI, see https://github.com/Nemocas/Nemo.jl/runs/4129208599?check_suite_focus=true#step:7:1132:
```julia
Test Summary:      | Pass  Total
plural.recognition |    2      2
    singular error: Bad ordering at 1,3

    singular error: Bad ordering at 2,4

    singular error: Matrix of polynomials violates the ordering condition
```
Might be related to the recent noncommutative additions?

**Comment by tthsqe12** [comment]
Singular has always been noisy. Maybe now it is noisy enough to be audible. Maybe @hannes14 can help up not print errors while still being able to check for them. This is a double edge sword: if singula errors and we dont explicitly chrck for it, the error will go unnoticed.

**Comment by hannes14** [comment]
Changing the error reporting of Singular is easy: just point the function pointer WerrorS_callback to a routine of your choice.
Here it shows that a G-algebra was defined which did not meet the requirements:
x_i*x_j < D_ij

**Comment by fingolfin** [comment]
Note that we do set `WerrorS_callback` to `WerrorS_and_reset` in `siInit`. Problem is that it still prints to stderr:
```C
/*
   This is the non-temporary callback for all errors (unless the temporary
   ones are in use by call_interpreter). It is probably safest to log the error
   to both singular_error and stderr, so that a missing libSingular.check_error
   does not cause error to go completely unnoticed.
*/
static void WerrorS_and_reset(const char * s)
{
    errorreported = 0;
    if (!singular_error.empty())
        singular_error += ".  ";
    singular_error += s;
    /* and, copied from WerrorS in Singular:*/
    fwrite("    singular error: ", 1, 20, stderr);
    fwrite(s, 1, strlen(s), stderr);
    fwrite("\n", 1, 1, stderr);
    fflush(stderr);
}
```
We could disable the printing there, but then we risk missing errors as we don't check `libSingular.have_error()` in enough places, I think :/.

In an ideal world, `WerrorS_and_reset` could just throw a Julia exception (that's essentially how the corresponding error handler in GAP works). Unfortunately, we can't do that here, as the Singular interpreter would be left in a random possibly broken state (leaking memory etc.) 

So the next best I can think of would be to add a flag to `libsingular-julia` which enables/disables the printing in `WerrorS_and_reset`. Then code which *does* check for errors can turn off the printing, do its thing, then at the end when it checks for errors also turn it back on. We could probably put this into a helper function to make it easy to use in lots of places.

**Comment by tthsqe12** [comment]
I like this solution, which won't need any global flags for configuration: initially the c++ error string in libsingular is empty of course, and the only way to clear it is via libsingular.check_error. When singular wants to report an error, we dump the current error string(s) to stderr if there are any and append the new error string that singular wants to report. This way all of the uncaught error messages will appear together, with O(n^2) messages reported in total for n uncaught errors in a row. And, correctly reporting singular's errors without letting them accumulate past 1 will result in no noise to stderr.
