### ISSUE TITLE
Odd `QuotientRing` test

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Singular.jl#508]
While trying to understand something about `QuotientRing` I came across this test (which according to `git blame` was added by @tthsqe12):
```
@testset "sideal.GAlgebra" begin

   R, (z, u, v, w) = PolynomialRing(QQ, ["z", "u", "v", "w"])
   G, (z, u, v, w) = GAlgebra(R, Singular.Matrix(R, [0 -1 -1 -1; 0 0 -1 -1; 0 0 0 -1; 0 0 0 0]),
                                 Singular.Matrix(R, [0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0]))

   @test_throws Exception QuotientRing(G, std(Ideal(R, [x])))
   @test_throws Exception QuotientRing(G, Ideal(R, [x], twosided = true))

   I = Ideal(G, [z^2, u^2, v^2, w^2, z*u*v - w]; twosided = true)
   Q, (z, u, v, w) = QuotientRing(G, std(I))
   @test Q isa GPolyRing
end
```

What I don't understand is the first `@test_throws` because it does `Ideal(R, [x])` but `x` is not even defined in this test. So I am guessing the exception being thrown is not the one we are looking for -- it'll be an `UndefVarError` or perhaps `x` does have a value, but not one in `R`. 

Or perhaps I am missing something?

**Comment by tthsqe12** [comment]
yup, that is a typo x -> z or u or v or w

**Comment by fingolfin** [comment]
OK, good. There is another `x`, too, probably the same. This shows that one shouldn't just check for `Exception` but really the concrete exception type, else such things happen

**Comment by tthsqe12** [comment]
What would you like to understand about QuotientRing? It is just like `qring r = (ideal);` in the singular language. Not sure how to document it: it would be a "QuotientRing constructs the quotient ring" kind of situation.
