### ISSUE TITLE
Call to arnoldClassify fails

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Singular.jl#585]
Disclaimer: I already posted this on slack and in various email communications, but was asked to make it an issue, instead.

The problem is the following:
```julia
using Oscar

function arnold_classify(f::MPolyElem)
  R = parent(f)
  o = negdegrevlex(gens(R))
  SR = singular_poly_ring(R, o.o)
  Sf = SR(f)
  result = Singular.LibArnoldclassify.arnoldClassify(Sf) # <--- problematic line
end

R, (x,y,z) = QQ["x", "y", "z"]

f = x^2 + y^2 + z^3

arnold_classify(f) 
```

This throws the following error:
```
ERROR: unrecognized object with Singular type number 539
Note that if Singular.jl cannot interpret the type, it is doubtful that a interpreter procedure returning such a type can be useful to Singular.jl.
Note also that Singular.jl does not support the attributes used by the interpreter.
Finally, Singular.lookup_library_symbol can be used to fetch the current value of global variables stored in the interpreter.
```

It seems that on the singular side, they wrapped the output in a fancy type that can not be digested. See also [this](https://www.singular.uni-kl.de/Manual/4-3-0/sing_1862.htm#SEC1943) documentation. Is there anything we can do about it?

**Comment by tthsqe12** [comment]
The return is a `newstruct`, which generates several problems even from within the singular language itself. Admittedly, in this case the members of the `newstruct` are all just plain strings, but, in general, `newstruct`s do not contain enough information for Singular.jl to translate them into valid julia objects.

**Comment by HechtiDerLachs** [comment]
Ok, thanks for looking into this. As far as I understand, there is no quick solution to this at this point? Also, given @afkafkafk13's last mail, we might be able to get similar results through other libraries. So I will try that for the moment.

**Comment by fingolfin** [comment]
It might be possible for someone who knows how to write Singular code (e.g. @afkafkafk13) to write a little helper function in Singular which performs the call you want, then "massages" the output into a format that Singular.jl can deal with. Then you could load that helper function once via `Singular.libSingular.call_interpreter` and then later call it at will?

**Comment by fingolfin** [comment]
That helper function could e.g. concatenate all those strings and integers into one big string, with a "safe" separator string between the various values, say `|`. Then a single string is returned which some Julia code can easily split again into the right parts. Not nice, but easy to do

**Comment by hannes14** [comment]
Here is such a wrapper for arnoldClassify: https://github.com/Singular/Singular/commit/a1f059e25e9de96b7fff2e4ae92504281fa605f1
