### ISSUE TITLE
Better automatic Singular banner hiding

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Singular.jl#611]
My students are writing a package which depends on Oscar. Loading their package in Julia 1.8.2 shows the Oscar banner, but also the Singular and Polymake banners. We have logic in place which is supposed to prevent this. Perhaps it needs to be update in a similar fashion to what @thofma did in https://github.com/oscar-system/GAP.jl/pull/826 ?

(Perhaps we should move this logic into a helper function and put it into a helper package that is then used by GAP.jl, Singular.jl, Polymake.jl -- this way we only need to update this and a few other things in only one place? Or even without the package, if there was an identical helper function used in all three packages, updating it would be easier).

See also https://github.com/oscar-system/Polymake.jl/issues/412

**Comment by thofma** [comment]
At the moment, in Nemo and Hecke, we suppress the banner as soon as a package does inside its module `using Hecke` for example. By this I mean that package `A` has `module A; using Hecke; end` inside `A/src/A.jl`. Should the OSCAR banner be suppressed in this case case? So far the answer has been no. It should always be printed.

**Comment by fingolfin** [comment]
Resolved by PR #668
