### ISSUE TITLE
OSCAR regression in `homological-algebra_test.jl`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Singular.jl#627]
Since the update for Singular_jll and libsingular_julia_jll updates from PR #625, the OscarCI tests reported a failure. Earlier today I couldn't reproduce this locally, but now I realized that this was because I'd run the wrong test.

So here is how to reproduce it in a Julia env where I dev'ed both Oscar and Singular:
```
julia> using Oscar
[...]

julia> pkgversion(Oscar.Singular.Singular_jll)
v"403.201.0+0"

julia> R, (x, y, z) = polynomial_ring(QQ, ["x", "y", "z"]);

julia> F = free_module(R, 1);

julia> I = ideal(R, [x*z-z, x*y-y, x])
ideal(x*z - z, x*y - y, x)

julia> depth(I, F)
-1
```
The Oscar.jl test suite expects that last command to return 3 instead (specifically, the test in `test/Modules/homological-algebra_test.jl`, line 67ff).

Note that `depth(I,F)` ultimately calls `Singular.LibHomolog.depth`. I noticed that `homolog.lib` was last changed this February, and in general a bunch of changes were applied to `depth` since the last time we update Singular_jll.

**Comment by thofma** [comment]
Great, so it was not me.

**Comment by thofma** [comment]
Would also be great to hear from @hannes14 which test showed green indicating that this would not break Oscar before merging. Then we can fix it and make sure that it does not happen again.

**Comment by fingolfin** [comment]
The OscarCI tests for "matching" showed red. Bit we could not reproduce it locally, so we decided to move forward as we did not make a release yet. If we can't resolve it today, we'll revert master

**Comment by fingolfin** [comment]
(I take full responsibility)

**Comment by fingolfin** [comment]
I've reverted the changes on `master` for now, to unbreak OscarCI tests elsewhere, and will re-submit the changes in it in a fresh PR.

**Comment by thofma** [comment]
Thanks for the explanation. I think reverting is the right thing to do for now. It was blocking also all downstream tests in AbstractAlgebra, Nemo, Hecke etc. This is how I noticed.
