### ISSUE TITLE
Inconsistent output of `prune_with_map_projection`

### ISSUE THREAD

**Issue by RafaelDavidMohr** [oscar-system/Singular.jl#796]
The output of `prune_with_map_projection` is not consistent between the zero module and other modules. Consider:

```
julia> R, (x, y) = polynomial_ring(QQ, ["x", "y"]);

julia> F = FreeModule(R, 1);

julia> v = F([zero(R)]);

julia> M = Singular.Module(R, v);

julia> prune_with_map_projection(M)
(Singular Module over Singular polynomial ring (QQ),(x,y),(dp(2),C), with Generators:
0, [0], Int32[0])
```
The last entry of this output should tell me which generators of the ambient free module of `M` were kept around as part of a minimal generating system of `F/M`. So in this case it should be `Int32[1]` instead.

**Comment by hannes14** [comment]
fixed with https://github.com/Singular/Singular/commit/5704a442d5557973dbede7f6f4f317bf9402aeff
