### ISSUE TITLE
convert / coerce n_Z into AbstractAlgebra.ZZ and/or Nemo.ZZ

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#80]
`AbstractAlgebra.ZZ(Singular.ZZ(1))
`
fails with
`ERROR: MethodError: no method matching (::AbstractAlgebra.Integers{BigInt})(::n_Z)`

Neither do `convert(Int, Singular.ZZ(1))` and `convert(BigInt, Singular.ZZ(1))` work.

Similarly
`Nemo.ZZ(Singular.ZZ(1))`
fails with
`ERROR: MethodError: no method matching (::FlintIntegerRing)(::n_Z)`

I think such coercions / conversions would be a helpful feature.

**Comment by wbhart** [comment]
I agree that both

```
Nemo.ZZ(Singular.ZZ(1))
```

and 

```
convert(Int, Singular.ZZ(1))
convert(BigInt, Singular.ZZ(1))
```

would be useful. I don't know if it is supported by the Singular library itself or not. But if not, we could get Hans to implement something, perhaps.

**Comment by sebasguts** [comment]
@wbhart The coeff rings have functions to convert to Int and MPZ, respectively.
You might want to look for `cfInt` and `cfMPZ`.

**Comment by wbhart** [comment]
Thanks @sebasguts

**Comment by heiderich** [comment]
With pull request #117 

`convert(BigInt, Singular.ZZ(1))`

is possible. 

`convert(Int, Singular.ZZ(1))`

would work, but in general I fear that there is no lossless conversion from `n_Z` to `Int`.

**Comment by wbhart** [comment]
It's fine to define a convert function for that, e.g. in Julia itself:

```
julia> convert(Int, BigInt(123))
123

julia> convert(Int, BigInt(12349873249873249872348732749832))
ERROR: InexactError: Int64(Int64, 12349873249873249872348732749832)
Stacktrace:
 [1] Int64(::BigInt) at ./gmp.jl:344
 [2] convert(::Type{Int64}, ::BigInt) at ./number.jl:7
 [3] top-level scope at none:0
```

We should simply do the same thing they do.
