### ISSUE TITLE
no method (::Rationals)(::Int64, ::Int64)

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#81]
The documentation contains the example 

```
f = QQ(-12, 7)

h = numerator(QQ)
k = denominator(QQ)
m = abs(f)
```

However there seems to be no suitable constructor:

```
julia> QQ(-12,7)
ERROR: MethodError: no method matching (::Rationals)(::Int64, ::Int64)
```

**Comment by wbhart** [comment]
Works for me.

The definition is in src/julia/Rational.jl

```
function (R::Rationals{T})(b::Integer, c::Integer) where T <: Integer
   return Rational{T}(b, c)
end
```

**Comment by heiderich** [comment]
You refer to `src/julia/Rational.jl`? Just "using Singular" this does not work for me.

**Comment by wbhart** [comment]
Which documentation are you referring to?

**Comment by wbhart** [comment]
Oh gosh. I didn't even remember we had written any docs for Singular.jl.

So yeah, that's a bug.

**Comment by heiderich** [comment]
See #83.
