### ISSUE TITLE
convert / coerce AbstractAlgebra.QQ into Singular.QQ

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#84]
I think it would be useful to convert / coerce `AbstractAlgebra.QQ` rational numbers into `Singular.QQ`. This is currently not possible:

```
julia> Singular.QQ(one(AbstractAlgebra.QQ))
ERROR: MethodError: no method matching (::Rationals)(::Rational{BigInt})

julia> convert(n_Q, one(AbstractAlgebra.QQ))
ERROR: MethodError: Cannot `convert` an object of type Rational{BigInt} to an object of type n_Q

```

**Comment by heiderich** [comment]
With #85 the following variant will be possible:

Singular.QQ(one(AbstractAlgebra.qq))

**Comment by heiderich** [comment]
With #87 the following is possible:

`Singular.QQ(one(AbstractAlgebra.QQ))`

**Comment by wbhart** [comment]
Merged.
