### ISSUE TITLE
coercion of Nemo.QQ into Singular.QQ

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#86]
It would be helpful to be able to coerce rationals from Nemo.QQ into Singular.QQ as follows:

`Singular.QQ(Nemo.QQ(1//2))`

**Comment by wbhart** [comment]
Agreed, but this is a low level issue. I will ask Hans if there is such a conversion implemented in Singular already.

**Comment by hannes14** [comment]
There is a routine to construct n_Q from gmp-integers (mpz_t): n_InitMPZ, but (currently) none
for mpq_t or pairs of mpz_t

**Comment by wbhart** [comment]
Thanks Hans.

**Comment by wbhart** [comment]
@heiderich It seems there isn't a way to do this efficiently at a low level, even in Singular. I would recommend converting first to Julia BigInts and then from there to Singular rationals. That's not efficient, but that is all that is implemented at present.

Obviously this will eventually improve as we work on the low level interfacing to make it more efficient.

**Comment by heiderich** [comment]
@wbhart Maybe one could use #87 in case it gets merged? Then one would only need to convert from `Nemo.QQ` into `Rational{BigInt}` first, as in the following example

`Singular.QQ(convert(Rational{BigInt}, one(Nemo.QQ)))`
