### ISSUE TITLE
divrem, div and divides missing for spoly

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#90]
I can't see an implementation of these in Singular, (for polynomials over a Euclidean ring, where divrem makes sense in the coefficient ring), though I might have overlooked something. @hannes14 

Certainly divides should exist when working over a Euclidean ring. I can of course push divrem to the "optional" interface if it is not considered important.

**Comment by wbhart** [comment]
Also check that remove and valuation work once these are defined. Otherwise AbstractAlgebra may need some work to make the generic functions there apply to Singular polys.

**Comment by fieker** [comment]
On Wed, Feb 06, 2019 at 08:47:27AM -0800, wbhart wrote:
> I can't see an implementation of these in Singular, (for polynomials over a Euclidean ring, where divrem makes sense in the coefficient ring), though I might have overlooked something. @hannes14 
> 
What is this functino supposed to be doing? divrem is, I thought, a
euclidean operation thus should be supported for univariate over a
field.
Possible one can extend this to univ over a ring when the divisor is
monic (invertable lead) or the leading coeff divides enough coeffs.
What would be the mathematical definition of divrem for spoly?
> Certainly divides should exist when working over a Euclidean ring. I can of course push divrem to the "optional" interface if it is not considered important.
> 
should (needs to) be there for all rings. Nothing to do with euclidean

**Comment by wbhart** [comment]
If you want students to be able to implement Buchberger they will need more than divrem for univariates over a field.

https://en.wikipedia.org/wiki/Gr%C3%B6bner_basis#Reduction

**Comment by fieker** [comment]
On Thu, Feb 07, 2019 at 01:12:48AM -0800, wbhart wrote:
> If you want students to be able to implement Buchberger they will need more than divrem for univariates over a field.
> 
Yep, but this not called divrem, divrem is euclidean (in my mind)
> https://en.wikipedia.org/wiki/Gr%C3%B6bner_basis#Reduction
they call it red....
You can have a divrem(f, Array{...}) but the result is only well defined
if the Array is a Groebner basis and you want full reduction.
Given that the Buchberger's only want exactly what is in the wiki, this
is what I'd provide - under that name.

My opinion.

**Comment by wbhart** [comment]
As the wikipedia article says, the reduction algorithm is exactly ordinary Euclidean division with remainder in the univariate case. For that reason it is also called the multivariate division algorithm.

Remember that the multivariate module is also used to implement sparse univariates, for which you certainly want the function to be called divrem so that the generic code works.

**Comment by wbhart** [comment]
As for ideal division, which I didn't mention, it is perfectly well defined, but depends on the ordering of the polynomial ring and the order of the basis vectors (unless it is a GB).

As for divisibility testing, this doesn't make sense over arbitrary rings. I'm not entirely sure what the most general ring would be. I can see it makes sense for gcd domains, though you then need to be able to distinguish when elements are associates, which may not be trivial. And I'm not presuming Singular has something implemented in such generality. We certainly don't.

**Comment by fieker** [comment]
On Thu, Feb 07, 2019 at 01:35:25AM -0800, wbhart wrote:
> As the wikipedia article says, the reduction algorithm is exactly ordinary Euclidean division with remainder in the univariate case. For that reason it is also called the multivariate division algorithm.
It's not the same for univariate: the red algorithm does only ONE step.
It is not even specified which coeff to reduce:

red(x^3+x^2+x+1, x+1) can return a remainder of
  x^3+x^2 (subtracting x+1)
  x^3 + 1 (subtracting x(x+1))
  x+1     (subtracting x^2(x+1))
at least accoring to the wiki page.

The euclidean division would need to iterate this as none of the above
is the euclidean result.

On the other hand, my understanding, but we can talk to the Groebner
people: in Buchberger you do not want to iterate, so you'd need a
different function and/or arguments to select.

Wiki claims it is a generalisation (possibly even a natural one), but
they don't claim that a restriction to univariate yields the old stuff.
If
 - you iterate this (until you cannot anymore)
 - and you have a list of polys forming a Groebner basis as the 2nd
   argument
Then this is well defined. Well, the remainder is, not the quotient.
In the case of univariate, any single poly is a Groebner basis.

> 
> Remember that the multivariate module is also used to implement sparse univariates, for which you certainly want the function to be called divrem so that the generic code works.
Well, yes and no: you essentially argue that sparse univariate need a
different type, it can use the same underlying code, but the univariates
have a different semantic
 - divrem -> euclidean
 - derivative -> no need to specify a variable
 - evaluate -> a point, not a sequence
 - no ordering
 - all ideals are principal -> different(?) easier(?) residue rings
and these are only the obvious ones.

**Comment by fieker** [comment]
On Thu, Feb 07, 2019 at 01:42:04AM -0800, wbhart wrote:
> As for ideal division, which I didn't mention, it is perfectly well defined, but depends on the ordering of the polynomial ring and the order of the basis vectors (unless it is a GB).
and more specs: do you always start reducing the lead term? This is not
part of the wiki!
> 
> As for divisibility testing, this doesn't make sense over arbitrary rings. I'm not entirely sure what the most general ring would be. I can see it makes sense for gcd domains, though you then need to be able to distinguish when elements are associates, which may not be trivial. And I'm not presuming Singular has something implemented in such generality. We certainly don't.
There is a conflict between math and programming: for any ring
divisibility testing makes sense.
We cannot perform this for all rings, but the question makes sense.
Thats why this is part of the interface for all rings - and sometimes
returns errors
 - not implemented for this ring
 - cannot decide for this ring

**Comment by wbhart** [comment]
The Singular reduce command has options to consider only the leading monomial or to do tail reduction. Anything that doesn't generalise Euclidean division in the univariate case obviously shouldn't be called that. But it is a perfectly well-defined operation and already implemented in AbstractAlgebra and Flint, (and in theory via reduce in Singular). It needs to exist so that division of multivariates that happen to be univariates works. We already have a separate reduce function in Singular.jl.

As for divisibility testing, you are right that mathematically the notion of divisibility can be defined generally. But our divides function returns the quotient, and this isn't well-defined in general. And obviously I am talking about the case that we know can actually be implemented. I'm not going to artificially restrict the domain of the inputs, but the reality is, it's most probably only implemented for polynomials over Euclidean rings. Our generic code certainly makes this assumption.

**Comment by fieker** [comment]
On Thu, Feb 07, 2019 at 02:07:11AM -0800, wbhart wrote:
> The Singular reduce command has options to consider only the leading monomial or to do tail reduction. Anything that doesn't generalise Euclidean division in the univariate case obviously shouldn't be called that. But it is a perfectly well-defined operation and already implemented in AbstractAlgebra and Flint, (and in theory via reduce in Singular). It needs to exist so that division of multivariates that happen to be univariates works. We already have a separate reduce function in Singular.jl.
What is the definition? The Wiki page deliberately never claims that.
In the end, be my guest. The function needs to be there as the
functionality is needed. However, as this is not euclidean, what will
actually happen if you try to call an HNF over this ring? Since the euc
interface is implemented this should work? I guess this goes into the
direction of my problem...
Having divrem, I'd expect gcd to work...
> 
> As for divisibility testing, you are right that mathematically the notion of divisibility can be defined generally. But our divides function returns the quotient, and this isn't well-defined in general. And obviously I am talking about the case that we know can actually be implemented. I'm not going to artificially restrict the domain of the inputs, but the reality is, it's most probably only implemented for polynomials over Euclidean rings. Our generic code certainly makes this assumption.
For Z/nZ the quotient is not well defined - nevertheless divides makes
sense and is there.
There is no need to decide this. We implement what we can and will
carefully not state that this will never be extended...

**Comment by wbhart** [comment]
Firstly, I was only referring to divrem(f, g) where f ang g are polynomials. If you think of this as reduction by an ideal generated by g, then that ideal is already Groebner basis (let's stick to polys over a field for now). Therefore, the result is even well-defined.

The wiki article carefully distinguished "one-step reduction" from reduction, and says that in the case of reduction by a single polynomial, the result is the same as Euclidean division in the univariate case.

"In the case of univariate polynomials, if G consists of a single element g, then h is the remainder of the Euclidean division of f by g, qg is the quotient and the division algorithm is exactly the process of lead-reduction. For this reason, some authors use the term multivariate division instead of reduction."

If you really want to talk about the case of ideal reduction, then of course you can choose to monomials in arbitrary order, but as the article points out, this is generally not done because it reintroduces monomials that have already been reduced. I'm going to make the assumption that Singular reduces monomials according to the ordering, which is also what we do in AbstractAlgebra/Flint.

**Comment by wbhart** [comment]
Even so, because an ideal generated by a single poly is already a GB, the result should be unique regardless of the order you do the reduction, in that specific case. It's just that some algorithms (such as reducing monomials according to the monomial ordering) are easier to reason about, and probably more efficient in practice.

**Comment by wbhart** [comment]
Ok, I see what you are getting at. My comment that you would need divrem for Buchberger is not correct. Buchberger is much better if you use lead reduction rather than complete reduction. And in AbstractAlgebra, we implement complete reduction, which is really only useful after you have computed a Groebner basis. (I suppose we could add an option to compute lead reduction, though the data format used there may not be as efficient as Singular's for that operation.)

**Comment by hannes14** [comment]
For division and remainder combined:
Singular provides R=idLift(A,B,&R,FALSE,TRUE,TRUE,&U) such that U[1,1]*R[1]=A[1]/B[1]+R[1].
(in the case for polynomials: U is a 1x1-matrix, R,A,B sideal from one polynomial)
For a single division: p_Divide

**Comment by wbhart** [comment]
Fixed in update_spoly branch.
