### ISSUE TITLE
adhoc divexact missing for spoly

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Singular.jl#91]
There are three cases:
* division by an integer
* division by a rational (where appropriate)
* division by an element of the coefficient ring

**Comment by hannes14** [comment]
- Division by an integer: number n=n_Init(i,r->cf);result=p_Div_nn(p_Copy(p,r),n,r);n_Delete(&n,r->cf);
- Division by n (of the coefficient ring): result=p_Div_nn(p_Copy(p,r),n,r);

**Comment by wbhart** [comment]
Thanks Hans!

**Comment by wbhart** [comment]
Implemented in update_spoly branch.
