### ISSUE TITLE
monomials and terms throw ERROR: UndefVarError: p_Head not defined

### ISSUE THREAD

**Issue by heiderich** [oscar-system/Singular.jl#95]
According to the announcement 
https://mail.mathematik.uni-kl.de/pipermail/oscar-dev/2019-February/000002.html
Singular.jl implements the interface described at 
https://nemocas.github.io/AbstractAlgebra.jl/latest/mpolynomial_rings/
and all the functions described at 
https://nemocas.github.io/AbstractAlgebra.jl/latest/mpolynomial/
are available for Singular polynomials.

However
```
using Singular
R,(x,y) = Singular.PolynomialRing(Singular.QQ, ["x", "y"] )
collect(monomials(x))
```
throws

`ERROR: UndefVarError: p_Head not defined`

The same is the case for

`collect(terms(x))`

**Comment by wbhart** [comment]
It works fine for me. My guess is either your Singular needs updating or your AbstractAlgebra.

**Comment by heiderich** [comment]
I was working with Singular.jl 5ac4100ea308f42066fa89d82e09b61ddc9d055e and https://github.com/Nemocas/AbstractAlgebra.jl/commit/f9e80ed84e6b0c1198135627a1b3bcb4eacadcb3. It turned out that for some reason parts of an old build were used. After removing Singular.jl completely and reinstalling it, it is working now. Please excuse the noise.
